#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_ForumEventSetting.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_ForumEventSetting.cshtml"
    using SnitzEvents.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_ForumEventSetting.cshtml")]
    public partial class _Views_Shared__ForumEventSetting_cshtml : System.Web.Mvc.WebViewPage<SnitzEvents.Models.CalForumAuth>
    {
        public _Views_Shared__ForumEventSetting_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\_ForumEventSetting.cshtml"
 using (Html.BeginForm("SaveForum", "Calendar",FormMethod.Post, new { @class = "form", id = "cal-forumAuth" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group panel-body\"");

WriteLiteral(">\r\n        <label>");

            
            #line 10 "..\..\Views\Shared\_ForumEventSetting.cshtml"
          Write(ResourceManager.GetLocalisedString("EventSettingTitle", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Shared\_ForumEventSetting.cshtml"
       Write(Html.EnumDropDownListFor(m=>m.Allowed,"Select Auth type","0",new{@class="form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\_ForumEventSetting.cshtml"
Write(Html.HiddenFor(m=>m.ForumId,new{id="cal-forumid"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </div>\r\n");

            
            #line 16 "..\..\Views\Shared\_ForumEventSetting.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
