#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_TopicEvent.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_TopicEvent.cshtml")]
    public partial class _Views_Shared__TopicEvent_cshtml : System.Web.Mvc.WebViewPage<SnitzEvents.Models.CalendarEventItem>
    {
        public _Views_Shared__TopicEvent_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Shared\_TopicEvent.cshtml"
 using (Html.BeginForm("SaveEvent", "Calendar", FormMethod.Post, new { @class = "form", id = "cal-addTopicEvent" }))
    {

            
            #line default
            #line hidden
WriteLiteral("<div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Shared\_TopicEvent.cshtml"
                          Write(ResourceManager.GetLocalisedString("TopicEventTitle", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Shared\_TopicEvent.cshtml"
   Write(Html.EditorForModel());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Shared\_TopicEvent.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Shared\_TopicEvent.cshtml"
         if (Model.TopicId > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <select>\r\n                <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\_TopicEvent.cshtml"
                             Write(ResourceManager.GetLocalisedString("ThisDate", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                <option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Shared\_TopicEvent.cshtml"
                             Write(ResourceManager.GetLocalisedString("AllDates", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                <option");

WriteLiteral(" value=\"3\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Shared\_TopicEvent.cshtml"
                             Write(ResourceManager.GetLocalisedString("FutureDates", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n            </select>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Shared\_TopicEvent.cshtml"
                                                        Write(ResourceManager.GetLocalisedString("ProcessDates", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</button></div>\r\n");

            
            #line 22 "..\..\Views\Shared\_TopicEvent.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

            
            #line 25 "..\..\Views\Shared\_TopicEvent.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
