#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ImageComment\_CommentIcon.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\ImageComment\_CommentIcon.cshtml"
    using WebSecurity = SnitzMembership.WebSecurity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ImageComment/_CommentIcon.cshtml")]
    public partial class _Views_ImageComment__CommentIcon_cshtml : System.Web.Mvc.WebViewPage<int>
    {
        public _Views_ImageComment__CommentIcon_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\ImageComment\_CommentIcon.cshtml"
 if (ViewBag.Comments == ResourceManager.GetLocalisedString("lblYes", "labels"))
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 190), Tuple.Create("\"", 266)
            
            #line 9 "..\..\Views\ImageComment\_CommentIcon.cshtml"
, Tuple.Create(Tuple.Create("", 197), Tuple.Create<System.Object, System.Int32>(Url.Action("Comments","ImageComment", new {id = Model, pagenum = 1})
            
            #line default
            #line hidden
, 197), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 267), Tuple.Create("\"", 338)
            
            #line 9 "..\..\Views\ImageComment\_CommentIcon.cshtml"
            , Tuple.Create(Tuple.Create("", 275), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("viewComment","PhotoAlbum")
            
            #line default
            #line hidden
, 275), false)
);

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" class=\"image-comment\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-comments-o fa-1_5x\"");

WriteLiteral("></i></a>\r\n");

            
            #line 10 "..\..\Views\ImageComment\_CommentIcon.cshtml"

}
else //if(WebSecurity.CurrentUserId != ViewBag.AuthorId)
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 502), Tuple.Create("\"", 578)
            
            #line 14 "..\..\Views\ImageComment\_CommentIcon.cshtml"
, Tuple.Create(Tuple.Create("", 509), Tuple.Create<System.Object, System.Int32>(Url.Action("Comments","ImageComment", new {id = Model, pagenum = 1})
            
            #line default
            #line hidden
, 509), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 579), Tuple.Create("\"", 649)
            
            #line 14 "..\..\Views\ImageComment\_CommentIcon.cshtml"
            , Tuple.Create(Tuple.Create("", 587), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("addComment","PhotoAlbum")
            
            #line default
            #line hidden
, 587), false)
);

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" class=\"image-comment\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-comment-o fa-1_5x\"");

WriteLiteral("></i></a>\r\n");

            
            #line 15 "..\..\Views\ImageComment\_CommentIcon.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
