//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMarks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bookmark {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bookmark() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookMarks.Resources.Bookmark", typeof(Bookmark).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bookmarked Topics.
        /// </summary>
        public static string IndexPageTitle {
            get {
                return ResourceManager.GetString("IndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh every 15 minutes.
        /// </summary>
        public static string Refresh_FifteenMinute {
            get {
                return ResourceManager.GetString("Refresh_FifteenMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh every 5 minutes.
        /// </summary>
        public static string Refresh_FiveMinute {
            get {
                return ResourceManager.GetString("Refresh_FiveMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh every minute.
        /// </summary>
        public static string Refresh_Minute {
            get {
                return ResourceManager.GetString("Refresh_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not refresh.
        /// </summary>
        public static string Refresh_None {
            get {
                return ResourceManager.GetString("Refresh_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh every 10 minutes.
        /// </summary>
        public static string Refresh_TenMinute {
            get {
                return ResourceManager.GetString("Refresh_TenMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts in the past day.
        /// </summary>
        public static string Since_LastDay {
            get {
                return ResourceManager.GetString("Since_LastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts in the past hour.
        /// </summary>
        public static string Since_LastHour {
            get {
                return ResourceManager.GetString("Since_LastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts in the past month.
        /// </summary>
        public static string Since_LastMonth {
            get {
                return ResourceManager.GetString("Since_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts since last visit.
        /// </summary>
        public static string Since_LastVisit {
            get {
                return ResourceManager.GetString("Since_LastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts in the past week.
        /// </summary>
        public static string Since_LastWeek {
            get {
                return ResourceManager.GetString("Since_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts since I registered.
        /// </summary>
        public static string Since_Registration {
            get {
                return ResourceManager.GetString("Since_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to bookmark Topic.
        /// </summary>
        public static string tipBookmarkPost {
            get {
                return ResourceManager.GetString("tipBookmarkPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected bookmarks.
        /// </summary>
        public static string tipDeleteSelected {
            get {
                return ResourceManager.GetString("tipDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarked, click to remove bookmark.
        /// </summary>
        public static string tipRemoveBookmark {
            get {
                return ResourceManager.GetString("tipRemoveBookmark", resourceCulture);
            }
        }
    }
}
