#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
    using System.Collections.ObjectModel;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    using MemberFields;
    
    #line 3 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
    using MemberFields.Models;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
    using WebSecurity = SnitzMembership.WebSecurity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MemberFields/_ExProfilesEdit.cshtml")]
    public partial class _Views_MemberFields__ExProfilesEdit_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<MemberProfile>>
    {
        public _Views_MemberFields__ExProfilesEdit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
  
    var requiredString = "data-val='true' data-val-required='" + ResourceManager.GetLocalisedString("PropertyRequired","ErrorMessage") + "'";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
     foreach (MemberProfile item in Model)
    {
        var fieldName = ResourceManager.GetLocalisedString("usr" + item.PropertyName, "ExtProfile");
        if (item.PropertyName != "TimeZone")
        {


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 564), Tuple.Create("\"", 587)
            
            #line 17 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
, Tuple.Create(Tuple.Create("", 569), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 569), false)
);

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                 if (item.PropertyType == "S")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input ");

            
            #line 24 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                        if (item.Optional == 0)
                                       {
                                           
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                      Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                            
                                       }
            
            #line default
            #line hidden
WriteLiteral(" type=\"text\" class=\"form-control\" id=\"input_");

            
            #line 27 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                               Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 27 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                         Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 27 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                    Write(item.PropertyValue);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 27 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                    Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary profile-text\"");

WriteLiteral(" data-control=\"");

            
            #line 28 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i></button></span>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 30 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 33 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"

                }
                else if (item.PropertyType == "T")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <textarea ");

            
            #line 41 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                           if (item.Optional == 0)
                                          {
                                              
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                         Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                               
                                          }
            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" rows=\"4\" id=\"input_");

            
            #line 44 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                               Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 44 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                         Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 44 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                        Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\">");

            
            #line 44 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                    Write(item.PropertyValue);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary profile-text\"");

WriteLiteral(" data-control=\"");

            
            #line 45 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i></button></span>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 50 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"

                }
                else if (item.PropertyType == "N")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <input ");

            
            #line 57 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                    if (item.Optional == 0)
                                   {
                                       
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                  Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                        
                                   }
            
            #line default
            #line hidden
WriteLiteral(" type=\"number\" id=\"input_");

            
            #line 60 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                        Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"input_");

            
            #line 60 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                        Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-control inline numberinput\" value=\"");

            
            #line 60 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                           Write(item.PropertyValue);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: 120px;\" data-user=\"");

            
            #line 60 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                                 Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                            <span");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary profile-text\"");

WriteLiteral(" data-control=\"");

            
            #line 61 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                          Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i></button></span>\r\n");

WriteLiteral("                            ");

            
            #line 62 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 65 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "Z")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 69 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input ");

            
            #line 72 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                        if (item.Optional == 0)
                                       {
                                           
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                      Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                            
                                       }
            
            #line default
            #line hidden
WriteLiteral(" type=\"text\" class=\"form-control datetime\" id=\"input_");

            
            #line 75 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                        Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 75 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 75 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                             Write(item.PropertyValue);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 75 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                             Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary profile-text\"");

WriteLiteral(" data-control=\"");

            
            #line 76 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i></button></span>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 78 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 81 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "D")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 85 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input ");

            
            #line 88 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                        if (item.Optional == 0)
                                       {
                                           
            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                      Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                            
                                       }
            
            #line default
            #line hidden
WriteLiteral(" type=\"text\" class=\"form-control date\" id=\"input_");

            
            #line 91 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                    Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 91 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                              Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 91 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                         Write(item.PropertyValue);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 91 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                         Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary profile-text\"");

WriteLiteral(" data-control=\"");

            
            #line 92 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i></button></span>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 94 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 97 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "X")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 101 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input ");

            
            #line 104 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                        if (item.Optional == 0)
                                       {
                                           
            
            #line default
            #line hidden
            
            #line 106 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                      Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 106 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                            
                                       }
            
            #line default
            #line hidden
WriteLiteral(" type=\"text\" class=\"form-control time\" id=\"input_");

            
            #line 107 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                    Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 107 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                              Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 107 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                         Write(item.PropertyValue);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 107 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                         Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary profile-text\"");

WriteLiteral(" data-control=\"");

            
            #line 108 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i></button></span>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 110 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n\r\n                    </div>\r\n");

            
            #line 114 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "C")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral("></label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                                <label>\r\n                                    <" +
"input ");

            
            #line 122 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                            if (item.Optional == 0)
                                           {
                                               
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                          Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                
                                           }
            
            #line default
            #line hidden
WriteLiteral(" id=\"input_");

            
            #line 125 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                  Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"checkbox\" class=\"profile-check\" value=\"1\" data-user=\"");

            
            #line 125 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                 Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 125 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                   Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 125 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                        Write(item.PropertyValue == "1" ? Html.Raw("checked") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral("> ");

            
            #line 125 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                                                                          Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </label>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 128 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 131 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "O")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 135 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <select ");

            
            #line 137 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                     if (item.Optional == 0)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 139 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                   Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 139 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                         
                                    }
            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control profile-select\" id=\"input_");

            
            #line 140 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                               Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 140 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                         Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 140 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                        Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

            
            #line 141 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 141 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                 foreach (var prop in item.PropertyOptions)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 9028), Tuple.Create("\"", 9041)
            
            #line 143 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
, Tuple.Create(Tuple.Create("", 9036), Tuple.Create<System.Object, System.Int32>(prop
            
            #line default
            #line hidden
, 9036), false)
);

WriteLiteral(" ");

            
            #line 143 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                           if (item.PropertyValue == prop)
                                                          {
                                                              
            
            #line default
            #line hidden
            
            #line 145 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                         Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 145 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                   
                                                          }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 147 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                   Write(prop);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n");

            
            #line 149 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </select>\r\n");

WriteLiteral("                            ");

            
            #line 151 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 154 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "M")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 158 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                            <select ");

            
            #line 160 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                     if (item.Optional == 0)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 162 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                   Write(String.Format(requiredString, item.PropertyName));

            
            #line default
            #line hidden
            
            #line 162 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                         
                                    }
            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control profile-selectmulti\" id=\"input_");

            
            #line 163 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                    Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");

            
            #line 163 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                              Write(item.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\" data-user=\"");

            
            #line 163 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                             Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\" multiple>\r\n");

            
            #line 164 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 164 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                 foreach (var prop in item.PropertyOptions)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 10399), Tuple.Create("\"", 10412)
            
            #line 166 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
, Tuple.Create(Tuple.Create("", 10407), Tuple.Create<System.Object, System.Int32>(prop
            
            #line default
            #line hidden
, 10407), false)
);

WriteLiteral(" ");

            
            #line 166 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                           if (item.PropertyValue.Contains(prop + "|"))
                                                          {
                                                              
            
            #line default
            #line hidden
            
            #line 168 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                         Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 168 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                   
                                                          }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 170 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                   Write(prop);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n");

            
            #line 172 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </select>\r\n");

WriteLiteral("                            ");

            
            #line 174 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 177 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "H")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 181 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n");

            
            #line 183 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 183 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                             foreach (var prop in item.PropertyOptions)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <label");

WriteLiteral(" class=\"radio-inline\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"profile-radio\"");

WriteLiteral(" type=\"radio\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11494), Tuple.Create("\"", 11519)
            
            #line 186 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
   , Tuple.Create(Tuple.Create("", 11501), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 11501), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 11520), Tuple.Create("\"", 11549)
, Tuple.Create(Tuple.Create("", 11525), Tuple.Create("input_", 11525), true)
            
            #line 186 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                 , Tuple.Create(Tuple.Create("", 11531), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 11531), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 11550), Tuple.Create("\"", 11563)
            
            #line 186 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 11558), Tuple.Create<System.Object, System.Int32>(prop
            
            #line default
            #line hidden
, 11558), false)
);

WriteLiteral(" data-user=\"");

            
            #line 186 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                          Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 186 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                            if (item.PropertyValue == prop)
                                                                                                                                                                                           {
                                                                                                                                                                                               
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                          Write(Html.Raw("checked"));

            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                                   
                                                                                                                                                                                           }
            
            #line default
            #line hidden
WriteLiteral("/>");

            
            #line 189 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                         Write(prop);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </label>\r\n");

            
            #line 191 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 191 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                           Write(Html.Raw("&nbsp;"));

            
            #line default
            #line hidden
            
            #line 191 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                   
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 193 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 196 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }
                else if (item.PropertyType == "V")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 200 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                         Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n");

            
            #line 202 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 202 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                             foreach (var prop in item.PropertyOptions)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <label");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" class=\"profile-radio\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13014), Tuple.Create("\"", 13039)
            
            #line 205 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
   , Tuple.Create(Tuple.Create("", 13021), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 13021), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 13040), Tuple.Create("\"", 13069)
, Tuple.Create(Tuple.Create("", 13045), Tuple.Create("input_", 13045), true)
            
            #line 205 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                 , Tuple.Create(Tuple.Create("", 13051), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 13051), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13070), Tuple.Create("\"", 13083)
            
            #line 205 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 13078), Tuple.Create<System.Object, System.Int32>(prop
            
            #line default
            #line hidden
, 13078), false)
);

WriteLiteral(" data-user=\"");

            
            #line 205 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                          Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"\"");

WriteLiteral(" ");

            
            #line 205 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                     if (item.PropertyValue == prop)
                                                                                                                                                                                                    {
                                                                                                                                                                                                        
            
            #line default
            #line hidden
            
            #line 207 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                   Write(Html.Raw("checked"));

            
            #line default
            #line hidden
            
            #line 207 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                                            
                                                                                                                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral("/>");

            
            #line 208 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                                                                                  Write(prop);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </label>\r\n");

            
            #line 210 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 211 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                       Write(Html.ValidationMessage(item.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 214 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

            
            #line 216 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 14090), Tuple.Create("\"", 14113)
            
            #line 219 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
, Tuple.Create(Tuple.Create("", 14095), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 14095), false)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-sm-4 flip text-right\"");

WriteLiteral(">");

            
            #line 221 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                     Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n                        <select");

WriteLiteral(" class=\"form-control inline profile-tzselect\"");

WriteAttribute("name", Tuple.Create(" name=\"", 14373), Tuple.Create("\"", 14398)
            
            #line 223 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
  , Tuple.Create(Tuple.Create("", 14380), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 14380), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 14399), Tuple.Create("\"", 14422)
            
            #line 223 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                          , Tuple.Create(Tuple.Create("", 14404), Tuple.Create<System.Object, System.Int32>(item.PropertyName
            
            #line default
            #line hidden
, 14404), false)
);

WriteLiteral(" data-user=\"");

            
            #line 223 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                                                                                     Write(WebSecurity.CurrentUserId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

            
            #line 224 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 224 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                              
                                string forumTimeZoneId = item.PropertyValue;

                                ReadOnlyCollection<TimeZoneInfo> timeZones = TimeZoneInfo.GetSystemTimeZones();

                                foreach (TimeZoneInfo timeZoneInfo in timeZones)
                                {
                                    if (forumTimeZoneId == timeZoneInfo.Id)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <option");

WriteAttribute("value", Tuple.Create(" value=\"", 14972), Tuple.Create("\"", 14996)
            
            #line 233 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
, Tuple.Create(Tuple.Create("", 14980), Tuple.Create<System.Object, System.Int32>(timeZoneInfo.Id
            
            #line default
            #line hidden
, 14980), false)
);

WriteLiteral(" selected>");

            
            #line 233 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                             Write(timeZoneInfo.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 234 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <option");

WriteAttribute("value", Tuple.Create(" value=\"", 15210), Tuple.Create("\"", 15234)
            
            #line 237 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
, Tuple.Create(Tuple.Create("", 15218), Tuple.Create<System.Object, System.Int32>(timeZoneInfo.Id
            
            #line default
            #line hidden
, 15218), false)
);

WriteLiteral(">");

            
            #line 237 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                                                    Write(timeZoneInfo.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 238 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
                                    }

                                }
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n                        </select>\r\n                    </div>\r\n                " +
"</div>                \r\n            </div>\r\n");

            
            #line 246 "..\..\Views\MemberFields\_ExProfilesEdit.cshtml"
        }
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
