#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    using BbCodeFormatter;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    using MemberFields;
    
    #line 5 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    using MemberFields.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    using SnitzDataModel.Extensions;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    using WebSecurity = SnitzMembership.WebSecurity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MemberFields/_ExProfilesView.cshtml")]
    public partial class _Views_MemberFields__ExProfilesView_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<MemberProfile>>
    {
        public _Views_MemberFields__ExProfilesView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
 foreach (MemberProfile item in Model)
{
    var displayVal = item.PropertyValue;
    var fieldName = ResourceManager.GetLocalisedString("usr" + item.PropertyName, "ExtProfile");
    if (item.Private == 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n                <label>");

            
            #line 19 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                  Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                 if (item.PropertyType == "T")
                {
                    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
               Write(Html.Raw(BbCodeProcessor.Format(displayVal, true, true)));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                                                                             
                }
                else if (item.PropertyType == "M")
                {
                    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
               Write(Html.Raw(BbCodeProcessor.Format(displayVal.Replace("|", "\n"), true, true)));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                                                                                                
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
               Write(displayVal);

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                               
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n\r\n        </div>\r\n");

            
            #line 37 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    }
    else if (item.MemberId == WebSecurity.CurrentUserId || User.IsAdministrator())
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group private\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n                <label>");

            
            #line 42 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                  Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n");

            
            #line 45 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                 if (item.PropertyType == "T")
                {
                    
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
               Write(Html.Raw(BbCodeProcessor.Format(displayVal, true, true)));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                                                                             
                }
                else if (item.PropertyType == "M")
                {
                    
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
               Write(Html.Raw(BbCodeProcessor.Format(displayVal.Replace("|", "\n"), true, true)));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                                                                                                
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
               Write(displayVal);

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
                               
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n\r\n        </div>\r\n");

            
            #line 60 "..\..\Views\MemberFields\_ExProfilesView.cshtml"
    }

}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
