#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\MemberFields\_ExProfileView.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    using MemberFields;
    
    #line 2 "..\..\Views\MemberFields\_ExProfileView.cshtml"
    using MemberFields.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MemberFields/_ExProfileView.cshtml")]
    public partial class _Views_MemberFields__ExProfileView_cshtml : System.Web.Mvc.WebViewPage<MemberProfile>
    {
        public _Views_MemberFields__ExProfileView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\MemberFields\_ExProfileView.cshtml"
  
    var displayVal = Model.PropertyValue;
    var fieldName = ResourceManager.GetLocalisedString("usr" + Model.PropertyName, "ExtProfile"); 
    if (Model.PropertyName == "TimeZone")
    {
        DateTime usertime = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, Model.PropertyValue);
        displayVal = usertime.ToString("HH:mm");
        fieldName = ResourceManager.GetLocalisedString("usrLocalTime","labels");
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n        <label>");

            
            #line 16 "..\..\Views\MemberFields\_ExProfileView.cshtml"
          Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\MemberFields\_ExProfileView.cshtml"
   Write(displayVal);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
