#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    using MemberFields;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MemberFields/_FieldCreateEdit.cshtml")]
    public partial class _Views_MemberFields__FieldCreateEdit_cshtml : System.Web.Mvc.WebViewPage<MemberFields.Models.ExtendedProfile>
    {
        public _Views_MemberFields__FieldCreateEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
  
    var fieldName = ResourceManager.GetLocalisedString("usrFieldName", "ExtProfile");
    var fieldType = ResourceManager.GetLocalisedString("usrFieldType", "ExtProfile");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times; </button>\r\n    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
                       Write(ResourceManager.GetLocalisedString("usrEditTitle", "ExtProfile"));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n</div>\r\n<div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"min-width: 360px;\"");

WriteLiteral(">\r\n    <section");

WriteLiteral(" id=\"field-create-box\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
         using (Ajax.BeginForm("FieldCreateEdit", "MemberFields",
            new AjaxOptions() { HttpMethod = "POST", OnSuccess = "fieldSuccess" },
            new { enctype = "multipart/form-data", id = "create-field-form" }))
        {
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
       Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
       Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
                                                 Write(fieldName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.EditorFor(model => model.FieldName, new { htmlAttributes = new { @class = "form-control field-name" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.ValidationMessageFor(model => model.FieldName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span");

WriteLiteral(" class=\"field-name-err\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">Invalid character</span>\r\n                </div>\r\n            </div>\r\n          " +
"  <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Description</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", rows = 4 } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
                                                 Write(fieldType);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.EditorFor(model => model.FieldType, new { htmlAttributes = new { @class = "form-control", rows = 4 } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.ValidationMessageFor(model => model.FieldType, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"options-create-box\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Options for Select Items seperate with |</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.EditorFor(model => model.OptionsString, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Default Value</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 53 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.EditorFor(model => model.DefaultValue, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
               Write(Html.ValidationMessageFor(model => model.DefaultValue, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Optional</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label>\r\n                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"Optional\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" ");

            
            #line 62 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
                                                                         Write(Model.Optional == 1 ? Html.Raw("checked") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral("> \r\n                        </label>\r\n                    </div>\r\n               " +
" </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Private</label>\r\n                <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label>\r\n                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"Private\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" ");

            
            #line 72 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
                                                                        Write(Model.Private == 1 ? Html.Raw("checked") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral("> \r\n                        </label>\r\n                    </div>\r\n               " +
" </div>\r\n            </div>\r\n\r\n        </div>\r\n");

            
            #line 79 "..\..\Views\MemberFields\_FieldCreateEdit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </section>\r\n\r\n</div>\r\n<div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-3 col-md-9\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" class=\"btn btn-sm btn-primary cancel\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"reset\"");

WriteLiteral(" value=\"Reset\"");

WriteLiteral(" class=\"btn btn-sm btn-warning \"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" class=\"btn btn-sm btn-success\"");

WriteLiteral(" onclick=\" saveProfileField() \"");

WriteLiteral(@"/>
        </div>
    </div>
</div>

<script>
    $(document)
        .ready(function() {
            if ($("".field-type-select"").length > 0) {
                if ($(""#FieldType"").val() === ""O"" || $(""#FieldType"").val() === ""M"" || $(""#FieldType"").val() === ""H"" || $(""#FieldType"").val() === ""V"") {
                    $(""#options-create-box"").show();
                } else {
                    $(""#options-create-box"").hide();
                }
            }
        });
</script>");

        }
    }
}
#pragma warning restore 1591
