#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Widgets\Admin.cshtml"
    using ForumWidgets.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/Admin.cshtml")]
    public partial class _Views_Widgets_Admin_cshtml : System.Web.Mvc.WebViewPage<System.Collections.Generic.List<ForumWidgets.Models.ForumWidget>>
    {
        public _Views_Widgets_Admin_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");



WriteLiteral(@"
<h5>Html Widgets</h5>
<hr class=""title""/>
    <div class=""row-fluid clearfix"">
    <div class=""pull-left""></div>
    </div> 
<table class=""table table-condensed"">
    <thead>
        <tr>
            <th class=""col-xs-3"">Name</th>
            <th class=""col-xs-8"">Html</th>
            <th class=""col-xs-1""></th>
        </tr>
    </thead>
    <tbody>
");


            
            #line 19 "..\..\Views\Widgets\Admin.cshtml"
         foreach (ForumWidget widget in Model)
        {
            using (Html.BeginForm("Save","Widgets"))
            {


            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td class=\"col-xs-3\">");


            
            #line 25 "..\..\Views\Widgets\Admin.cshtml"
                                    Write(Html.HiddenFor(m=>widget.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 26 "..\..\Views\Widgets\Admin.cshtml"
                   Write(Html.TextBoxFor(m=>widget.Name,new {@class="form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td class=\"col-xs-8\">\r\n         " +
"               ");


            
            #line 29 "..\..\Views\Widgets\Admin.cshtml"
                   Write(Html.TextAreaFor(m=>widget.HtmlString,new {@class="form-control",rows="6"}));

            
            #line default
            #line hidden
WriteLiteral(@"
                    </td>
                    <td class=""col-xs-1"">
                        <button type=""submit"" class=""btn btn-xs btn-primary"" title=""Save Widget"" data-toggle=""tooltip""><i class=""fa fa-save""></i></button>
                        <a href=""");


            
            #line 33 "..\..\Views\Widgets\Admin.cshtml"
                            Write(Url.Action("Delete","Widgets",new{id=widget.Id}));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-xs btn-danger\" title=\"Delete Widget\" data-toggle=\"tooltip\"><i cl" +
"ass=\"fa fa-trash\"></i></a>\r\n       \r\n                    </td>\r\n                " +
"</tr>   \r\n");


            
            #line 37 "..\..\Views\Widgets\Admin.cshtml"
            } 
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n    <tfoot>\r\n        <tr>\r\n            <td colspan=\"3\">\r\n          " +
"     <a href=\"");


            
            #line 43 "..\..\Views\Widgets\Admin.cshtml"
                   Write(Url.Action("AddWidget", "Widgets"));

            
            #line default
            #line hidden
WriteLiteral(@""" data-toggle=""modal"" data-target=""#modal-addwidget"" id=""addwidget-link"" class=""btn btn-xs btn-success"" title=""Add Widget"">Add</a>
            </td>
        </tr>
    </tfoot>
</table>

    <!-- Begin modal-container -->
    <div class=""modal fade"" id=""modal-addwidget"" tabindex=""-1"" role=""dialog"" aria-labelledby=""myModalLabel"" aria-hidden=""true"">
        <div id="""" class=""modal-dialog"">
            <div class=""modal-content"">
                <div class=""container text-center"">
                <i class=""fa fa-spinner fa-pulse fa-3x fa-fw""></i>
                <span class=""sr-only"">Loading...</span></div>
            </div>
        </div>
    </div>  
");


DefineSection("scripts", () => {

WriteLiteral(@"
<script>
    $(document).ready(function () {
        $.validator.unobtrusive.parse(""#addWidget"");

        $(document).on('submit','#addWidget',function (event) {

            event.preventDefault();
            var validator = $(this).validate();
            validator.showErrors();

            if ($(this).valid()) {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function() {
                        $('#modal-addwidget').modal('hide');
                        var dlg = BootstrapDialog.success(""Widget Added"");
                        setTimeout(function () {
                            dlg.close();
                            location.reload();
                        }, 1500);
                    },
                    error: function(error) {
                        BootstrapDialog.alert({
                            title: 'Error',
                            message: error
                        });
                    }
                });
            }

            return false;
        });
    });
</script>    
");


});


        }
    }
}
#pragma warning restore 1591
