#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\popAddWidget.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/popAddWidget.cshtml")]
    public partial class _Views_Widgets_popAddWidget_cshtml : System.Web.Mvc.WebViewPage<ForumWidgets.Models.ForumWidget>
    {
        public _Views_Widgets_popAddWidget_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("        <div class=\"modal-header\">\r\n            <button type=\"button\" class=\"clos" +
"e\" data-dismiss=\"modal\" aria-hidden=\"true\">&times; </button>\r\n            <h4 cl" +
"ass=\"modal-title\" id=\"myModalLabel\">Add Widget</h4>\r\n        </div>\r\n");


            
            #line 7 "..\..\Views\Widgets\popAddWidget.cshtml"
     using (Html.BeginForm("Add", "Widgets", FormMethod.Post, new { id = "addWidget", @class="form-horizontal" }))
    {    

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"modal-body\">\r\n        <div class=\"container\">\r\n              " +
"  ");


            
            #line 11 "..\..\Views\Widgets\popAddWidget.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 12 "..\..\Views\Widgets\popAddWidget.cshtml"
           Write(Html.ValidationSummary(false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 13 "..\..\Views\Widgets\popAddWidget.cshtml"
           Write(Html.HiddenFor(m=>m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"form-group\">\r\n                            <" +
"label class=\"control-label col-sm-2\">Name</label>\r\n                            <" +
"div class=\"col-sm-4\">");


            
            #line 16 "..\..\Views\Widgets\popAddWidget.cshtml"
                                             Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                            <div class=""col-sm-6""></div>
                        </div>
                        <div class=""form-group"">
                            <label class=""control-label col-sm-2"">Widget code</label>
                            <div class=""col-sm-10"">");


            
            #line 21 "..\..\Views\Widgets\popAddWidget.cshtml"
                                              Write(Html.TextAreaFor(m => m.HtmlString, new { @class = "form-control", rows="6" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </div>\r\n\r\n        </div>\r\n        </div>\r\n");



WriteLiteral("        <div class=\"modal-footer\">\r\n            <button type=\"button\" class=\"btn " +
"btn-warning\" data-dismiss=\"modal\">");


            
            #line 27 "..\..\Views\Widgets\popAddWidget.cshtml"
                                                                          Write(ResourceManager.GetLocalisedString("btnCancel", "labels"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            <input type=\"submit\" class=\"btn btn-primary\" value=\"");


            
            #line 28 "..\..\Views\Widgets\popAddWidget.cshtml"
                                                           Write(ResourceManager.GetLocalisedString("btnSave", "labels"));

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n        </div>\r\n");


            
            #line 30 "..\..\Views\Widgets\popAddWidget.cshtml"
    }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
