#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\PostThanks\_Members.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PostThanks/_Members.cshtml")]
    public partial class _Views_PostThanks__Members_cshtml : System.Web.Mvc.WebViewPage<System.Collections.Generic.List<string>>
    {
        public _Views_PostThanks__Members_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(">\r\n    <li><b>");

            
            #line 4 "..\..\Views\PostThanks\_Members.cshtml"
      Write(ResourceManager.GetLocalisedString("Thanked", "Thanks"));

            
            #line default
            #line hidden
WriteLiteral("</b></li>\r\n");

            
            #line 5 "..\..\Views\PostThanks\_Members.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\PostThanks\_Members.cshtml"
     foreach (var member in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>");

            
            #line 7 "..\..\Views\PostThanks\_Members.cshtml"
       Write(member);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 8 "..\..\Views\PostThanks\_Members.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
