#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\PostThanks\_Profile.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PostThanks/_Profile.cshtml")]
    public partial class _Views_PostThanks__Profile_cshtml : System.Web.Mvc.WebViewPage<PostThanks.Models.PostThanksProfile>
    {
        public _Views_PostThanks__Profile_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"panel panel-thanks\"");

WriteLiteral(">\r\n    <label>");

            
            #line 5 "..\..\Views\PostThanks\_Profile.cshtml"
      Write(ResourceManager.GetLocalisedString("lblReceived", "Thanks"));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"badge badge-success\"");

WriteAttribute("title", Tuple.Create(" title=\"", 215), Tuple.Create("\"", 339)
            
            #line 5 "..\..\Views\PostThanks\_Profile.cshtml"
                                  , Tuple.Create(Tuple.Create("", 223), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("lblReceived", "Thanks")
            
            #line default
            #line hidden
, 223), false)
            
            #line 5 "..\..\Views\PostThanks\_Profile.cshtml"
                                                                                              , Tuple.Create(Tuple.Create(" ", 283), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("thanks", "Thanks")
            
            #line default
            #line hidden
, 284), false)
);

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\PostThanks\_Profile.cshtml"
                                                                                                                                                                                                                                                        Write(Model.Received);

            
            #line default
            #line hidden
WriteLiteral("</span> ");

            
            #line 5 "..\..\Views\PostThanks\_Profile.cshtml"
                                                                                                                                                                                                                                                                               Write(ResourceManager.GetLocalisedString("thanks", "Thanks"));

            
            #line default
            #line hidden
WriteLiteral("</label><br />\r\n    <label>");

            
            #line 6 "..\..\Views\PostThanks\_Profile.cshtml"
      Write(ResourceManager.GetLocalisedString("given", "Thanks"));

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"badge badge-primary\"");

WriteAttribute("title", Tuple.Create(" title=\"", 555), Tuple.Create("\"", 617)
            
            #line 6 "..\..\Views\PostThanks\_Profile.cshtml"
                           , Tuple.Create(Tuple.Create("", 563), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("given", "Thanks")
            
            #line default
            #line hidden
, 563), false)
);

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(">");

            
            #line 6 "..\..\Views\PostThanks\_Profile.cshtml"
                                                                                                                                                                                   Write(Model.Given);

            
            #line default
            #line hidden
WriteLiteral("</span></label>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
