#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
    using PhotoAlbum.Views.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
    using SnitzDataModel.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PhotoAlbum/_MemberSlideShow.cshtml")]
    public partial class _Views_PhotoAlbum__MemberSlideShow_cshtml : System.Web.Mvc.WebViewPage<PhotoAlbum.ViewModels.ImageModel>
    {
        public _Views_PhotoAlbum__MemberSlideShow_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
  
    ViewBag.Title = ViewBag.Username + "'s Photo Album";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(" style=\"text-align:center; position: relative;height: 640px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(" id=\"SlideshowNav\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"left col-xs-1 col-xs-offset-4\"");

WriteLiteral(" href=\"#myCarousel\"");

WriteLiteral(" role=\"button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 437), Tuple.Create("\"", 503)
            
            #line 11 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
              , Tuple.Create(Tuple.Create("", 445), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("Previous", "General")
            
            #line default
            #line hidden
, 445), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"fa fa-chevron-left fa-2x\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                 Write(ResourceManager.GetLocalisedString("Previous", "General"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n            <div");

WriteLiteral(" class=\"small col-xs-2\"");

WriteLiteral(" id=\"galleryImageLbl\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
           Write(Html.Raw(ViewBag.title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <a");

WriteLiteral(" class=\"right col-xs-1\"");

WriteLiteral(" href=\"#myCarousel\"");

WriteLiteral(" role=\"button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 908), Tuple.Create("\"", 970)
            
            #line 18 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
, Tuple.Create(Tuple.Create("", 916), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("Next", "General")
            
            #line default
            #line hidden
, 916), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"fa fa-chevron-right fa-2x\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                 Write(ResourceManager.GetLocalisedString("Next", "General"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" id=\"SlideshowImages\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1333), Tuple.Create("\"", 1415)
            
            #line 27 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
, Tuple.Create(Tuple.Create("", 1339), Tuple.Create<System.Object, System.Int32>(Html.ImageUrlFor(Model.CurrentImage.Location, Model.CurrentImage.Timestamp)
            
            #line default
            #line hidden
, 1339), false)
);

WriteLiteral(" data-id=\"");

            
            #line 27 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                                                                                             Write(Model.CurrentIdx);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-user=\"");

            
            #line 27 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                                                                                                                            Write(ViewBag.Username);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" alt=\"No Image\"");

WriteLiteral(" style=\"max-height: 95%; max-width: 95%;\"");

WriteLiteral(" id=\"galleryImage\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(" id=\"SlideshowNavB\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"left col-xs-1 col-xs-offset-4\"");

WriteLiteral(" href=\"#myCarousel\"");

WriteLiteral(" role=\"button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1742), Tuple.Create("\"", 1808)
            
            #line 30 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                 , Tuple.Create(Tuple.Create("", 1750), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("Previous", "General")
            
            #line default
            #line hidden
, 1750), false)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"fa fa-chevron-left fa-2x\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                     Write(ResourceManager.GetLocalisedString("Previous", "General"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </a>\r\n                <div");

WriteLiteral(" class=\"small col-xs-2\"");

WriteLiteral(" id=\"galleryImageFooterLbl\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
               Write(Html.Raw(ViewBag.footer));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <a");

WriteLiteral(" class=\"right col-xs-1\"");

WriteLiteral(" href=\"#myCarousel\"");

WriteLiteral(" role=\"button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2248), Tuple.Create("\"", 2310)
            
            #line 37 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
  , Tuple.Create(Tuple.Create("", 2256), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("Next", "General")
            
            #line default
            #line hidden
, 2256), false)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"fa fa-chevron-right fa-2x\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                     Write(ResourceManager.GetLocalisedString("Next", "General"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </a>\r\n            </div>\r\n        </div>\r\n        <input" +
"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"json-data\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2608), Tuple.Create("\"", 2635)
            
            #line 43 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
, Tuple.Create(Tuple.Create("", 2616), Tuple.Create<System.Object, System.Int32>(ViewBag.JsonParams
            
            #line default
            #line hidden
, 2616), false)
);

WriteLiteral(@" />
    </div>

    <script>
                $('#SlideshowNav,#SlideshowNavB')
                    .on('click',
                        '.left',
                        function() {
                            var idx = $('#galleryImage').data(""id"") - 1;
                            var searchdata = $(""#json-data"").val();
                            //clearTimeout(imgTimeout);
                            $.ajax({
                                type: ""GET"",
                                url: '");

            
            #line 56 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                 Write(Url.Action("Next", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral(@"' +
                                    '/' +
                                    idx +
                                    '?member=' +
                                    $('#galleryImage').data(""user"") +
                                    '&searchparams=' +
                                    searchdata,
                                success: function(data) {
                                    $('#galleryImage')
                                        .fadeOut(500,
                                            function() {
                                                $('#galleryImage').attr('src', data.src);
                                                $('#galleryImage').fadeIn(500);
                                            });
                                    $('#galleryImage').data(""id"", data.idx);
                                    $('#galleryImageLbl').html(data.title);
                                    $('#galleryImageFooterLbl').html(data.desc);
                                    //if (timing > 0) {
                                    //    imgTimeout = window.setTimeout(loop, timing);
                                    //}
                                },
                                error: function(error) {
                                    //clearTimeout(imgTimeout);
                                    BootstrapDialog.alert({
                                        title: '");

            
            #line 80 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                           Write(ResourceManager.GetLocalisedString("lblError", "labels"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                                        message: error
                                    });
                                }
                            });
                        });
                $('#SlideshowNav,#SlideshowNavB')
                    .on('click',
                        '.right',
                        function() {
                            var idx = $('#galleryImage').data(""id"") + 1;
                            var searchdata = $(""#json-data"").val();
                            //clearTimeout(imgTimeout);
                            $.ajax({
                                type: ""GET"",
                                url: '");

            
            #line 95 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                 Write(Url.Action("Next", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral(@"' +
                                    '/' +
                                    idx +
                                    '?member=' +
                                    $('#galleryImage').data(""user"") +
                                    '&searchparams=' +
                                    searchdata,
                                success: function(data) {
                                    $('#galleryImage')
                                        .fadeOut(500,
                                            function() {
                                                $('#galleryImage').attr('src', data.src);
                                                $('#galleryImage').fadeIn(500);
                                            });
                                    $('#galleryImage').data(""id"", data.idx);
                                    $('#galleryImageLbl').html(data.title);
                                    $('#galleryImageFooterLbl').html(data.desc);
                                    //if (timing > 0) {
                                    //    imgTimeout = window.setTimeout(loop, timing);
                                    //}
                                },
                                error: function(error) {
                                    //clearTimeout(imgTimeout);
                                    BootstrapDialog.alert({
                                        title: '");

            
            #line 119 "..\..\Views\PhotoAlbum\_MemberSlideShow.cshtml"
                                           Write(ResourceManager.GetLocalisedString("lblError", "labels"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                        message: error\r\n                     " +
"               });\r\n                                }\r\n                         " +
"   });\r\n                        });\r\n    </script>\r\n");

        }
    }
}
#pragma warning restore 1591
