#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using PetaPoco;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using PhotoAlbum.Views.Helpers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using Snitz.Base;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using SnitzConfig;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using SnitzCore.Extensions;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    using SnitzDataModel.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PhotoAlbum/AlbumNew.cshtml")]
    public partial class _Views_PhotoAlbum_AlbumNew_cshtml : System.Web.Mvc.WebViewPage<PhotoAlbum.ViewModels.SpeciesAlbum>
    {
        public _Views_PhotoAlbum_AlbumNew_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
  
    ViewBag.Title = ResourceManager.GetLocalisedString("mnuCommonAlbum");
    ViewBag.PageTitle = ResourceManager.GetLocalisedString("mnuCommonAlbum");
    ViewBag.ShowThumbs = Model.Thumbs;

    string controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
    int pagecount = Convert.ToInt32(ViewBag.PageCount);
    int page = ViewBag.Page;
    int intLow = page - 1;
    int intHigh = page + 3;
    if (intLow < 1) { intLow = 1; }
    if (intHigh > pagecount) { intHigh = pagecount; }
    if (intHigh - intLow < 5) { while ((intHigh < intLow + 4) && intHigh < pagecount) { intHigh++; } }
    if (intHigh - intLow < 5) { while ((intLow > intHigh - 4) && intLow > 1) { intLow--; } }

    string sortIcon = ViewBag.SortDir == "desc" ? "<i class=\"fa fa-sort-desc\"></i>" : "<i class=\"fa fa-sort-asc\"></i>";



            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1113), Tuple.Create("\"", 1169)
, Tuple.Create(Tuple.Create("", 1120), Tuple.Create<System.Object, System.Int32>(Href("~/Content/plugincss/jquery.bsPhotoGallery.min.css")
, 1120), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(@">
    <style>

        ul {
            padding: 0 0 0 0;
            margin: 0 0 40px 0;
        }

            ul li {
                list-style: none;
                margin-bottom: 10px;
            }

        .text {
            /*font-family: 'Bree Serif';*/
            color: #666;
            font-size: 11px;
            margin-bottom: 10px;
            padding: 12px;
            background: #fff;
        }
    </style>

");

});

WriteLiteral("<h5>\r\n");

WriteLiteral("    ");

            
            #line 56 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 56 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                    if (User.Identity.IsAuthenticated)
    {
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
Write(Html.ActionLink(" ", "UploadFile", "PhotoAlbum", null, new { @class = "gallery-link pull-right fa fa-upload fa-1_5x", title = ResourceManager.GetLocalisedString("lblUpload", "PhotoAlbum"), data_toggle = "tooltip" }));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                                                                                                                                             }

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n<hr");

WriteLiteral(" class=\"title\"");

WriteLiteral(" />\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n");

            
            #line 61 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
     using (Html.BeginForm())
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label>");

            
            #line 68 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                          Write(ResourceManager.GetLocalisedString("lblSearchin", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"GroupFilter \"");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">");

            
            #line 71 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                     Write(ResourceManager.GetLocalisedString("lblGroup", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 72 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.SrchId, new { @class = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"SrchUser\"");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">");

            
            #line 75 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                 Write(ResourceManager.GetLocalisedString("Member", "General"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 76 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.SrchUser, new { @class = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"SrchSciName\"");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                    Write(ResourceManager.GetLocalisedString("lblScientificName", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 80 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.SrchSciName, new { @class = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"SrchLocName\"");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                    Write(ResourceManager.GetLocalisedString("lblLocalName", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 84 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.SrchLocName, new { @class = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"SrchDesc\"");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                 Write(ResourceManager.GetLocalisedString("lblDescription", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 88 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.SrchDesc, new { @class = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"GroupFilter \"");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">");

            
            #line 91 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                     Write(ResourceManager.GetLocalisedString("lblGroup", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 92 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.DropDownList("GroupFilter", Model.GroupList, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-group pull-right\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"SrchTerm\"");

WriteLiteral(">");

            
            #line 95 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                         Write(ResourceManager.GetLocalisedString("lblSearchFor", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                        ");

            
            #line 96 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.TextBoxFor(m => m.SrchTerm, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                 Write(ResourceManager.GetLocalisedString("Search", "labels"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </div>\r\n                </div>\r\n            </div>" +
"\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"width-check\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"Thumbs\"");

WriteLiteral(">");

            
            #line 104 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                       Write(ResourceManager.GetLocalisedString("lblSearchView", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</label>\r\n");

WriteLiteral("                        ");

            
            #line 105 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.Thumbs, new { id = "viewthumbs" }));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 105 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                               Write(ResourceManager.GetLocalisedString("lblShowThumbnails", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"SpeciesOnly\"");

WriteLiteral(">&nbsp;</label>\r\n");

WriteLiteral("                        ");

            
            #line 109 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                   Write(Html.CheckBoxFor(m => m.SpeciesOnly, new { id = "speciesonly" }));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 109 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                     Write(ResourceManager.GetLocalisedString("lblShowOnlySpecies", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-group pull-right\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" class=\"form-control checkbox-inline dropdown-menu1\"");

WriteLiteral(" id=\"album-sortby\"");

WriteLiteral(" name=\"SortBy\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"id\"");

WriteLiteral("\r\n                                            ");

            
            #line 116 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "id") { 
            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                      Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                  }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 117 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortId", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"date\"");

WriteLiteral("\r\n                                            ");

            
            #line 120 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "date") { 
            
            #line default
            #line hidden
            
            #line 120 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                        Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 120 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 121 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortDate", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"user\"");

WriteLiteral("\r\n                                            ");

            
            #line 124 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "user") { 
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                        Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 125 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortUser", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"desc\"");

WriteLiteral("\r\n                                            ");

            
            #line 128 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "desc") { 
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                        Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 129 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortDesc", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"file\"");

WriteLiteral("\r\n                                            ");

            
            #line 132 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "file") { 
            
            #line default
            #line hidden
            
            #line 132 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                        Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 132 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 133 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortFile", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"localname\"");

WriteLiteral("\r\n                                            ");

            
            #line 136 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "localname") { 
            
            #line default
            #line hidden
            
            #line 136 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                             Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 136 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                         }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 137 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortCommon", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"scientific\"");

WriteLiteral("\r\n                                            ");

            
            #line 140 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortBy == "scientific") { 
            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                              Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                          }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 141 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optSortScientific", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"</select>\r\n                            </span>\r\n                            <spa" +
"n");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"SortOrder\"");

WriteLiteral(" id=\"album-sortdesc\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"desc\"");

WriteLiteral("\r\n                                            ");

            
            #line 148 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortPage == "desc") { 
            
            #line default
            #line hidden
            
            #line 148 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                          Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 148 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 149 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optDesc", "Controls"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"    <option");

WriteLiteral(" value=\"asc\"");

WriteLiteral("\r\n                                            ");

            
            #line 152 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                             if (ViewBag.SortPage == "asc") { 
            
            #line default
            #line hidden
            
            #line 152 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                         Write(Html.Raw("selected"));

            
            #line default
            #line hidden
            
            #line 152 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 153 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                   Write(ResourceManager.GetLocalisedString("optAsc", "Controls"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n                                " +
"</select>\r\n                            </span>\r\n                            ");

WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">&nbsp;</div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n            <hr");

WriteLiteral(" class=\"title\"");

WriteLiteral(" />\r\n            <div>\r\n\r\n");

            
            #line 172 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                
            
            #line default
            #line hidden
            
            #line 172 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                 if (pagecount > 1)
                {


            
            #line default
            #line hidden
WriteLiteral("                    <ul");

WriteLiteral(" class=\"pager\"");

WriteLiteral(">\r\n");

            
            #line 176 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 176 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                         if (page > 1)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral("> ");

            
            #line 178 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                     Write(Html.ActionLink("<<", "Album", controllerName, new { pagenum = 1, sortOrder = ViewBag.SortPage }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 179 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                    Write(Html.ActionLink("<", "Album", controllerName, new { pagenum = page - 1, sortOrder = ViewBag.SortPage }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 180 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 183 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 183 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                         for (int i = intLow; i < intHigh + 1; i++)
                        {
                            if (i == page)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><span");

WriteLiteral(" class=\"pager-link-current\"");

WriteLiteral(">");

            
            #line 187 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                Write(Html.ActionLink(i + "", "Album", controllerName, new { pagenum = i, sortOrder = ViewBag.SortPage }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 188 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 191 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                        Write(Html.ActionLink(i + "", "Album", controllerName, new { pagenum = i, sortOrder = ViewBag.SortPage }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 192 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 194 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                         if (page < pagecount)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 196 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                    Write(Html.ActionLink(">", "Album", controllerName, new { pagenum = page + 1, sortOrder = ViewBag.SortPage }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 197 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                    Write(Html.ActionLink(">>", "Album", controllerName, new { pagenum = pagecount, sortOrder = ViewBag.SortPage }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 198 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n");

            
            #line 200 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 205 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n\r\n            ");

WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        <ul");

WriteLiteral(" class=\"row first\"");

WriteLiteral(">\r\n");

            
            #line 303 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
            
            
            #line default
            #line hidden
            
            #line 303 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
             foreach (var photo in Model.Images)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 18546), Tuple.Create("\"", 18568)
            
            #line 306 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
, Tuple.Create(Tuple.Create("", 18552), Tuple.Create<System.Object, System.Int32>(photo.ImageName
            
            #line default
            #line hidden
, 18552), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 18569), Tuple.Create("\"", 18630)
            
            #line 306 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
, Tuple.Create(Tuple.Create("", 18575), Tuple.Create<System.Object, System.Int32>(Html.ImageUrlFor(photo.Location,photo.Timestamp,false)
            
            #line default
            #line hidden
, 18575), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n                        \r\n                        <dl>\r\n");

            
            #line 310 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 310 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                             if (!string.IsNullOrWhiteSpace(photo.GroupName))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <dt>");

            
            #line 312 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                               Write(photo.GroupName);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n");

            
            #line 313 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            \r\n");

            
            #line 315 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 315 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                             if (!string.IsNullOrWhiteSpace(photo.CommonName))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <dd>");

            
            #line 317 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                               Write(photo.CommonName);

            
            #line default
            #line hidden
WriteLiteral(" <dfn>(");

            
            #line 317 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                       Write(photo.ScientificName);

            
            #line default
            #line hidden
WriteLiteral(")</dfn></dd>\r\n");

            
            #line 318 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <dd>");

            
            #line 320 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                           Write(photo.Description);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 320 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                               Write(photo.Views);

            
            #line default
            #line hidden
WriteLiteral(")</dd>\r\n                        </dl>\r\n                        \r\n                " +
"    </div>\r\n                </li>\r\n");

            
            #line 325 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n\r\n");

            
            #line 330 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                
            
            #line default
            #line hidden
            
            #line 330 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                 if (pagecount > 1)
                {


            
            #line default
            #line hidden
WriteLiteral("                    <ul");

WriteLiteral(" class=\"pager\"");

WriteLiteral(">\r\n");

            
            #line 334 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 334 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                         if (page > 1)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral("> ");

            
            #line 336 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                     Write(Html.ActionLink("<<", "Album", controllerName, new { pagenum = 1 }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 337 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                    Write(Html.ActionLink("<", "Album", controllerName, new { pagenum = page - 1 }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 338 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 341 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 341 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                         for (int i = intLow; i < intHigh + 1; i++)
                        {
                            if (i == page)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><span");

WriteLiteral(" class=\"pager-link-current\"");

WriteLiteral(">");

            
            #line 345 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                                Write(Html.ActionLink(i + "", "Album", controllerName, new { pagenum = i }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 346 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 349 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                        Write(Html.ActionLink(i + "", "Album", controllerName, new { pagenum = i }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 350 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 352 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                         if (page < pagecount)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 354 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                    Write(Html.ActionLink(">", "Album", controllerName, new { pagenum = page + 1 }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

WriteLiteral("                            <li><span");

WriteLiteral(" class=\"pager-link\"");

WriteLiteral(">");

            
            #line 355 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                                                    Write(Html.ActionLink(">>", "Album", controllerName, new { pagenum = pagecount }, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 356 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n");

            
            #line 358 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 363 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row text-center album-copyright\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 365 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
   Write(ResourceManager.GetLocalisedString("lblSpeciesCopy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"json-data\"");

WriteAttribute("value", Tuple.Create(" value=\"", 21351), Tuple.Create("\"", 21378)
            
            #line 369 "..\..\Views\PhotoAlbum\AlbumNew.cshtml"
, Tuple.Create(Tuple.Create("", 21359), Tuple.Create<System.Object, System.Int32>(ViewBag.JsonParams
            
            #line default
            #line hidden
, 21359), false)
);

WriteLiteral(" />\r\n<div");

WriteLiteral(" id=\"modal-gallery-upload\"");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" id=\"modal-gallery-upload-content\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21608), Tuple.Create("\"", 21639)
, Tuple.Create(Tuple.Create("", 21614), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/dropzone.min.js")
, 21614), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21686), Tuple.Create("\"", 21736)
, Tuple.Create(Tuple.Create("", 21692), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pluginjs/jquery.ui.position.min.js")
, 21692), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21783), Tuple.Create("\"", 21833)
, Tuple.Create(Tuple.Create("", 21789), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pluginjs/jquery.contextMenu.min.js")
, 21789), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21880), Tuple.Create("\"", 21932)
, Tuple.Create(Tuple.Create("", 21886), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pluginjs/snitz.gallery.upload.min.js")
, 21886), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21979), Tuple.Create("\"", 22027)
, Tuple.Create(Tuple.Create("", 21985), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pluginjs/snitz.photoalbum.min.js")
, 21985), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 22074), Tuple.Create("\"", 22127)
, Tuple.Create(Tuple.Create("", 22080), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pluginjs/jquery.bsPhotoGallery.min.js")
, 22080), false)
);

WriteLiteral(@"></script>


    <script>
        $(document).ready(function () {
            $('ul.first').bsPhotoGallery({
                ""classes"": ""col-lg-2 col-md-4 col-sm-3 col-xs-4 col-xxs-12"",
                ""hasModal"": true,
                //""fullHeight"" : false
            });

            try {
                Dropzone.autoDiscover = false;
            } catch (e) {
                console.log('Dropzone not loaded');
            }
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
