#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\PhotoAlbum\Index.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\PhotoAlbum\Index.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\PhotoAlbum\Index.cshtml"
    using MvcBreadCrumbs;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\PhotoAlbum\Index.cshtml"
    using PetaPoco;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\PhotoAlbum\Index.cshtml"
    using Snitz.Base;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\PhotoAlbum\Index.cshtml"
    using SnitzConfig;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\PhotoAlbum\Index.cshtml"
    using SnitzCore.Extensions;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Views\PhotoAlbum\Index.cshtml"
    using SnitzCore.Utility;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PhotoAlbum\Index.cshtml"
    using SnitzDataModel.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PhotoAlbum/Index.cshtml")]
    public partial class _Views_PhotoAlbum_Index_cshtml : System.Web.Mvc.WebViewPage<PetaPoco.Page<PhotoAlbum.Models.AlbumList>>
    {
        public _Views_PhotoAlbum_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\PhotoAlbum\Index.cshtml"
  
    ViewBag.Title = ResourceManager.GetLocalisedString("titleIndex", "PhotoAlbum");
    string sortIcon = ViewBag.SortDir == "asc" ? "<i class=\"fa fa-sort-asc\"></i>" : "<i class=\"fa fa-sort-desc\"></i>";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 17 "..\..\Views\PhotoAlbum\Index.cshtml"
  
    //check the culture so we can set the page direction and language
    CultureInfo ci = SessionData.Get<CultureInfo>("Culture");
    string clang = ci.TwoLetterISOLanguageName;
    bool isRighToLeft = SessionData.Get<bool>("isRighToLeft");


            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Views\PhotoAlbum\Index.cshtml"
Write(Html.Raw(Config.ThemeCss("plugincss/photoalbum.min.css")));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <style>\r\n\r\n        .modal-content {\r\n            max-width: 600px !importan" +
"t;\r\n            margin: 30px auto !important;\r\n        }\r\n    </style>\r\n\r\n");

});

DefineSection("breadcrumb", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Views\PhotoAlbum\Index.cshtml"
Write(Html.Raw(BreadCrumb.Display()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("sidebox", () => {

WriteLiteral("\r\n");

            
            #line 42 "..\..\Views\PhotoAlbum\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\PhotoAlbum\Index.cshtml"
     if (ClassicConfig.GetIntValue("INTFEATUREDPHOTO") == 1)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"side-box\"");

WriteLiteral(" id=\"fimage\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\PhotoAlbum\Index.cshtml"
                                     Write(Html.Action("FeaturedImage"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 45 "..\..\Views\PhotoAlbum\Index.cshtml"
    }

            
            #line default
            #line hidden
});

WriteLiteral("<h5>\r\n");

WriteLiteral("    ");

            
            #line 48 "..\..\Views\PhotoAlbum\Index.cshtml"
Write(ResourceManager.GetLocalisedString("h5Index", "PhotoAlbum"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 48 "..\..\Views\PhotoAlbum\Index.cshtml"
                                                                  if (User.Identity.IsAuthenticated)
    {
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\PhotoAlbum\Index.cshtml"
Write(Html.ActionLink(" ", "UploadFile", "PhotoAlbum", null, new { @class = "gallery-link pull-right fa fa-upload fa-1_5x", title = ResourceManager.GetLocalisedString("lblUpload", "PhotoAlbum"), data_toggle = "tooltip" }));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\PhotoAlbum\Index.cshtml"
                                                                                                                                                                                                                             }

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n<hr");

WriteLiteral(" class=\"title\"");

WriteLiteral(" />\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n                <form");

WriteAttribute("action", Tuple.Create(" action=\"", 1750), Tuple.Create("\"", 1876)
            
            #line 56 "..\..\Views\PhotoAlbum\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1759), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","PhotoAlbum",new{pagenum = ViewBag.Page, sortOrder = ViewBag.SortDir, sortCol = ViewBag.SortBy })
            
            #line default
            #line hidden
, 1759), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" name=\"term\"");

WriteLiteral(" id=\"term\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2026), Tuple.Create("\"", 2105)
            
            #line 58 "..\..\Views\PhotoAlbum\Index.cshtml"
                   , Tuple.Create(Tuple.Create("", 2040), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("lblUserFilter","PhotoAlbum")
            
            #line default
            #line hidden
, 2040), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2106), Tuple.Create("\"", 2133)
            
            #line 58 "..\..\Views\PhotoAlbum\Index.cshtml"
                                                                                             , Tuple.Create(Tuple.Create("", 2114), Tuple.Create<System.Object, System.Int32>(ViewBag.SearchTerm
            
            #line default
            #line hidden
, 2114), false)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i></button>\r\n                        </span>\r\n                    </div>\r\n    " +
"                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 64 "..\..\Views\PhotoAlbum\Index.cshtml"
                   Write(Html.ValidationSummary(false, "", new { @class = "list-group-item-info" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </form>\r\n            </div>\r\n\r\n    " +
"    </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 71 "..\..\Views\PhotoAlbum\Index.cshtml"
       Write(Html.Partial("_AlbumPager", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <table");

WriteLiteral(" class=\"table table-bordered table-condensed table-striped\"");

WriteAttribute("lang", Tuple.Create(" lang=\"", 2767), Tuple.Create("\"", 2780)
            
            #line 73 "..\..\Views\PhotoAlbum\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2774), Tuple.Create<System.Object, System.Int32>(clang
            
            #line default
            #line hidden
, 2774), false)
);

WriteAttribute("dir", Tuple.Create(" dir=\"", 2781), Tuple.Create("\"", 2820)
            
            #line 73 "..\..\Views\PhotoAlbum\Index.cshtml"
              , Tuple.Create(Tuple.Create("", 2787), Tuple.Create<System.Object, System.Int32>(isRighToLeft ?  "rtl" : "ltr" 
            
            #line default
            #line hidden
, 2787), false)
);

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"bg-primary\"");

WriteLiteral(">\r\n                    <th>\r\n");

WriteLiteral("                        ");

            
            #line 77 "..\..\Views\PhotoAlbum\Index.cshtml"
                   Write(Html.ActionLink(ResourceManager.GetLocalisedString("Member", "General"), "Index", new { pagenum = ViewBag.Page, sortOrder = ViewBag.SortUser, sortCol = "user" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 78 "..\..\Views\PhotoAlbum\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\PhotoAlbum\Index.cshtml"
                         if (ViewBag.SortBy == "user")
                        {
                            
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\PhotoAlbum\Index.cshtml"
                       Write(Html.Raw(sortIcon));

            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\PhotoAlbum\Index.cshtml"
                                               
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </th>\r\n                    <th>\r\n");

WriteLiteral("                        ");

            
            #line 84 "..\..\Views\PhotoAlbum\Index.cshtml"
                   Write(Html.ActionLink(ResourceManager.GetLocalisedString("lblImages", "PhotoAlbum"), "Index", new { pagenum = ViewBag.Page, sortOrder = ViewBag.SortCount, sortCol = "count" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 85 "..\..\Views\PhotoAlbum\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\PhotoAlbum\Index.cshtml"
                         if (ViewBag.SortBy == "count")
                        {
                            
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\PhotoAlbum\Index.cshtml"
                       Write(Html.Raw(sortIcon));

            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\PhotoAlbum\Index.cshtml"
                                               
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </th>\r\n                    <th>\r\n");

WriteLiteral("                        ");

            
            #line 91 "..\..\Views\PhotoAlbum\Index.cshtml"
                   Write(Html.ActionLink(ResourceManager.GetLocalisedString("lblLastPhoto", "PhotoAlbum"), "Index", new { pagenum = ViewBag.Page, sortOrder = ViewBag.SortDate, sortCol = "date" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 92 "..\..\Views\PhotoAlbum\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\PhotoAlbum\Index.cshtml"
                         if (ViewBag.SortBy == "date")
                        {
                            
            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\PhotoAlbum\Index.cshtml"
                       Write(Html.Raw(sortIcon));

            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\PhotoAlbum\Index.cshtml"
                                               
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </th>\r\n                </tr>\r\n            </thead>\r\n         " +
"   <tbody>\r\n");

            
            #line 100 "..\..\Views\PhotoAlbum\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\PhotoAlbum\Index.cshtml"
                 foreach (var album in Model.Items)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");

            
            #line 103 "..\..\Views\PhotoAlbum\Index.cshtml"
                       Write(Html.ActionLink(album.Username, "Member", new { id = album.Username, sortby = "date", sortorder = "desc" }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 104 "..\..\Views\PhotoAlbum\Index.cshtml"
                       Write(album.imgCount.ToLangNum());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 105 "..\..\Views\PhotoAlbum\Index.cshtml"
                       Write(album.imgLastUpload.ToSnitzDateTime().ToClientTime().ToFormattedString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 107 "..\..\Views\PhotoAlbum\Index.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n            <tfoot>\r\n                <tr>\r\n                " +
"    <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">");

            
            #line 112 "..\..\Views\PhotoAlbum\Index.cshtml"
                               Write(Model.CurrentPage.ToLangNum());

            
            #line default
            #line hidden
WriteLiteral(" of ");

            
            #line 112 "..\..\Views\PhotoAlbum\Index.cshtml"
                                                                 Write(Model.TotalPages.ToLangNum());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n            </tfoot>\r\n        </table>\r\n    </div>\r" +
"\n\r\n</div>\r\n<div");

WriteLiteral(" id=\"modal-gallery-upload\"");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral("\r\n     tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5081), Tuple.Create("\"", 5112)
, Tuple.Create(Tuple.Create("", 5087), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/dropzone.min.js")
, 5087), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5159), Tuple.Create("\"", 5211)
, Tuple.Create(Tuple.Create("", 5165), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pluginjs/snitz.gallery.upload.min.js")
, 5165), false)
);

WriteLiteral(@"></script>
    <script>
        $(document)
            .ready(function () {
                try {
                    Dropzone.autoDiscover = false;
                } catch (e) {
                    console.log(Snitzres.DZNotLoaded);
                }
            });
    </script>

");

});

        }
    }
}
#pragma warning restore 1591
