#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
    using SnitzDataModel.Extensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
    using SnitzEvents.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/CalendarEventItem.cshtml")]
    public partial class _Views_Shared_EditorTemplates_CalendarEventItem_cshtml_ : System.Web.Mvc.WebViewPage<SnitzEvents.Models.CalendarEventItem>
    {
        public _Views_Shared_EditorTemplates_CalendarEventItem_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("            ");

            
            #line 8 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
       Write(Html.HiddenFor(m=>m.TopicId,new{id="cal-topicid"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"StartDate\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                                                        Write(ResourceManager.GetLocalisedString("lblStartDate", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 11 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                 if (Model.TopicId > 0 && Model.StartDate.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control cal-dates\"");

WriteLiteral(" id=\"calendar-start-date\"");

WriteLiteral(" name=\"StartDate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 577), Tuple.Create("\"", 637)
            
            #line 13 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                                        , Tuple.Create(Tuple.Create("", 585), Tuple.Create<System.Object, System.Int32>(Model.StartDate.Value.ToString("dd MMM yyyy HH:mm")
            
            #line default
            #line hidden
, 585), false)
);

WriteLiteral("/>\r\n");

            
            #line 14 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control cal-dates\"");

WriteLiteral(" id=\"calendar-start-date\"");

WriteLiteral(" name=\"StartDate\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n");

            
            #line 18 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"EndDate\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                                                      Write(ResourceManager.GetLocalisedString("lblEndDate", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                 if (Model.EndDate.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control cal-dates\"");

WriteLiteral(" id=\"calendar-end-date\"");

WriteLiteral(" name=\"EndDate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1210), Tuple.Create("\"", 1268)
            
            #line 27 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                                   , Tuple.Create(Tuple.Create("", 1218), Tuple.Create<System.Object, System.Int32>(Model.EndDate.Value.ToString("dd MMM yyyy HH:mm")
            
            #line default
            #line hidden
, 1218), false)
);

WriteLiteral("/>\r\n");

            
            #line 28 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control cal-dates\"");

WriteLiteral(" id=\"calendar-end-date\"");

WriteLiteral(" name=\"EndDate\"");

WriteLiteral(" value=\"\"");

WriteLiteral("/>\r\n");

            
            #line 32 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                    <label>");

            
            #line 37 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                      Write(Html.CheckBoxFor(m => m.IsAllDayEvent, new { id = "event-allday" }));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 37 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                                                                                           Write(ResourceManager.GetLocalisedString("lblAllDay", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                </div>\r\n            </div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"cal-recur\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 41 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
                                            Write(ResourceManager.GetLocalisedString("lblRecurs", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
Write(Html.EnumDropDownListFor(m=>m.Recurs,new{@class="form-control",id="cal-recur"},""));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"cal-dow\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n");

            
            #line 45 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
      
        var daySources = new SelectList(Enum.GetValues(typeof(CalEnums.CalDays)).Cast<CalEnums.CalDays>().Select(v => new SelectListItem
        {
            Text = v.ToString(),
            Value = ((int)v).ToString()
        }).ToList(), "Value", "Text");

        
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 55 "..\..\Views\Shared\EditorTemplates\CalendarEventItem.cshtml"
   Write(Html.CheckBoxListFor(model => model.SelectedDays, daySources));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
