#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Bookmark\Index.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Bookmark/Index.cshtml")]
    public partial class _Views_Bookmark_Index_cshtml : System.Web.Mvc.WebViewPage<BookMarks.Models.BookmarkViewModel>
    {
        public _Views_Bookmark_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Bookmark\Index.cshtml"
  
    ViewBag.Title = @ResourceManager.GetLocalisedString("IndexTitle","BookMarks");
    ViewBag.PageTitle = @ResourceManager.GetLocalisedString("IndexPageTitle", "BookMarks");

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("sidebox", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"side-box\"");

WriteLiteral(">\r\n    </div>\r\n");

});

WriteLiteral("<h5>");

            
            #line 13 "..\..\Views\Bookmark\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n<hr");

WriteLiteral(" class=\"title\"");

WriteLiteral("/>\r\n");

            
            #line 15 "..\..\Views\Bookmark\Index.cshtml"
Write(Html.Partial("_Bookmarks"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n       \r\n        $(document).on(\'click\', \'#delete_button\', function (e) {\r\n   " +
"         e.preventDefault();\r\n            var delForm = $(this).closest(\'form\');" +
"\r\n            BootstrapDialog.confirm({\r\n                title: \'");

            
            #line 25 "..\..\Views\Bookmark\Index.cshtml"
                   Write(ResourceManager.GetLocalisedString("DeleteBookmarks","Bookmarks"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                message: \'<label>");

            
            #line 26 "..\..\Views\Bookmark\Index.cshtml"
                            Write(ResourceManager.GetLocalisedString("DeleteConfirm", "BookMarks"));

            
            #line default
            #line hidden
WriteLiteral(@"</label><br/>', callback: function (ok) {
                    if (ok) delForm.submit();
                }
            });

        });
        $('#checkAll').change(function () {
            var table = $(this).closest('table');
            $('td input:checkbox', table).prop('checked', this.checked);
        });
        var refresh = '");

            
            #line 36 "..\..\Views\Bookmark\Index.cshtml"
                  Write(ViewBag.RefreshSeconds);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n        if (refresh > 0)\r\n            setTimeout(\"window.location.reload();" +
"\", /* time you want to refresh in milliseconds */ refresh);\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
