#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Events\_Admin.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Events\_Admin.cshtml"
    using SnitzConfig;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Events\_Admin.cshtml"
    using SnitzEvents.Views.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Events/_Admin.cshtml")]
    public partial class _Views_Events__Admin_cshtml : System.Web.Mvc.WebViewPage<SnitzEvents.ViewModels.EventsAdminViewModel>
    {
        public _Views_Events__Admin_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <h4>Club/Society Lookup data</h4>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group col-xs-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Categories</label>\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Events\_Admin.cshtml"
   Write(Html.ListBox("CategoriesList", new SelectList(Model.Categories, "Key", "Value"), new { @class = "form-control", id = "cat-select" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"edit-event-cat\"");

WriteLiteral(" title=\"edit selected category\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-edit\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"add-event-cat\"");

WriteLiteral(" title=\"add new category\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-plus\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"del-event-cat\"");

WriteLiteral(" title=\"delete selected category\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-trash-o\"");

WriteLiteral("></i></a>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group col-xs-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Clubs</label>\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\Events\_Admin.cshtml"
   Write(Html.ListBox("ClubsList", new SelectList(Model.Clubs, "Key", "Value"), new { @class = "form-control", id = "club-select" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"edit-event-club\"");

WriteLiteral(" title=\"edit selected club\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-edit\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"add-event-club\"");

WriteLiteral(" title=\"add new club\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-plus\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"del-event-club\"");

WriteLiteral(" title=\"delete selected club\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-trash-o\"");

WriteLiteral("></i></a>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group col-xs-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Locations</label>\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Views\Events\_Admin.cshtml"
   Write(Html.ListBox("LocationsList", new SelectList(Model.Locations, "Key", "Value"), new { @class = "form-control", id = "loc-select" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"edit-event-loc\"");

WriteLiteral(" title=\"edit selected location\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-edit\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"add-event-loc\"");

WriteLiteral(" title=\"add new location\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-plus\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"del-event-loc\"");

WriteLiteral(" title=\"delete selected location\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-1_5x fa-trash-o\"");

WriteLiteral("></i></a>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\'listeditor\'");

WriteLiteral(" class=\'modal fade in\'");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times; </button>\r\n                <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"listeditorTitle\"");

WriteLiteral("></h5>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\'listeditorContainer\'");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container text-center\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-spinner fa-pulse fa-3x fa-fw\"");

WriteLiteral("></i>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Loading...</span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n " +
"   </div>\r\n</div>\r\n\r\n");

            
            #line 58 "..\..\Views\Events\_Admin.cshtml"
 using (Html.BeginScripts())
{

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3129), Tuple.Create("\"", 3175)
, Tuple.Create(Tuple.Create("", 3135), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.unobtrusive-ajax.min.js")
, 3135), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script>\r\n        $(document).ready(function() {\r\n            $(\'.del-event-c" +
"at\').on(\'click\', function (e) {\r\n                e.preventDefault();\r\n          " +
"      \r\n                BootstrapDialog.confirm({\r\n                    title: \'D" +
"elete Category\',\r\n                    message: \'<label>Are you sure you want to " +
"delete this Category? </label><br/>\', callback: function (ok) {\r\n               " +
"         if (ok) {\r\n                            var id = $(\'#cat-select\').val();" +
"\r\n                            deleteListItem(id,\'cat\');\r\n                       " +
" }\r\n                    }\r\n                });\r\n            });\r\n            $(\'" +
".del-event-club\').on(\'click\', function (e) {\r\n                e.preventDefault()" +
";\r\n                \r\n                BootstrapDialog.confirm({\r\n                " +
"    title: \'Delete Club\',\r\n                    message: \'<label>Are you sure you" +
" want to delete this Club? </label><br/>\', callback: function (ok) {\r\n          " +
"              if (ok) {\r\n                            var id = $(\'#club-select\')." +
"val();\r\n                            deleteListItem(id, \'club\');\r\n               " +
"         }\r\n                    }\r\n                });\r\n            });\r\n       " +
"     $(\'.del-event-loc\').on(\'click\', function (e) {\r\n                e.preventDe" +
"fault();\r\n                BootstrapDialog.confirm({\r\n                    title: " +
"\'Delete Location\',\r\n                    message: \'<label>Are you sure you want t" +
"o delete this Location? </label><br/>\', callback: function (ok) {\r\n             " +
"           if (ok) {\r\n                            var id = $(\'#loc-select\').val(" +
");\r\n                            deleteListItem(id, \'loc\');\r\n                    " +
"    }\r\n                    }\r\n                });\r\n                \r\n           " +
" });\r\n\r\n            $(\'.add-event-cat\').on(\'click\', function (e) {\r\n            " +
"    e.preventDefault();\r\n                $.get(window.SnitzVars.baseUrl + \'Event" +
"s/AddEditCategory/0\', function (data) {\r\n                    showForm(\'Add Categ" +
"ory\', data);\r\n                });\r\n\r\n            });\r\n            $(\'.add-event-" +
"club\').on(\'click\', function (e) {\r\n                e.preventDefault();\r\n        " +
"        $.get(window.SnitzVars.baseUrl + \'Events/AddEditClub/0\', function (data)" +
" {\r\n                    showForm(\'Add Club\', data);\r\n                });\r\n      " +
"      });\r\n            $(\'.add-event-loc\').on(\'click\', function (e) {\r\n         " +
"       e.preventDefault();\r\n                $.get(window.SnitzVars.baseUrl + \'Ev" +
"ents/AddEditLocation/0\', function (data) {\r\n                    showForm(\'Add Lo" +
"cation\', data);\r\n                });\r\n            });\r\n\r\n            $(\'.edit-ev" +
"ent-cat\').on(\'click\', function (e) {\r\n                e.preventDefault();\r\n     " +
"           var id = $(\'#cat-select\').val();\r\n                $.get(window.SnitzV" +
"ars.baseUrl + \'Events/AddEditCategory/\' + id, function (data) {\r\n               " +
"     showForm(\'Edit Category\', data);\r\n                });\r\n            });\r\n   " +
"         $(\'.edit-event-club\').on(\'click\', function (e) {\r\n                e.pre" +
"ventDefault();\r\n                var id = $(\'#club-select\').val();\r\n             " +
"   $.get(window.SnitzVars.baseUrl + \'Events/AddEditClub/\' + id, function (data) " +
"{\r\n                    showForm(\'Edit Club\', data);\r\n                });\r\n      " +
"      });\r\n            $(\'.edit-event-loc\').on(\'click\', function (e) {\r\n        " +
"        e.preventDefault();\r\n                var id = $(\'#loc-select\').val();\r\n " +
"               $.get(window.SnitzVars.baseUrl + \'Events/AddEditLocation/\' + id, " +
"function (data) {\r\n                    showForm(\'Edit Location\', data);\r\n       " +
"         });\r\n            });\r\n\r\n        });\r\n        function deleteListItem(id" +
", type) {\r\n            $.ajax({\r\n                type: \"POST\",\r\n                " +
"url: SnitzVars.baseUrl + \'Events/Delete/\' + id + \'?t=\' + type,\r\n                " +
"success: function (data) {\r\n                    if (data.success) {\r\n           " +
"             BootstrapDialog.alert(\r\n                            {\r\n            " +
"                    title: \"Event Info \",\r\n                                messa" +
"ge: data.responseText\r\n                            });\r\n                        " +
"location.reload();\r\n                        return false;\r\n                    }" +
"\r\n\r\n                },\r\n                error: function (result) {\r\n            " +
"        BootstrapDialog.alert(\r\n                        {\r\n                     " +
"       title: \"Event Error \",\r\n                            message: result\r\n    " +
"                    });\r\n                }\r\n            });\r\n        }\r\n\r\n      " +
"  function showForm(title,data) {\r\n            $(\'#listeditorContainer\').html(da" +
"ta);\r\n            $(\'#listeditorTitle\').html(title);\r\n            $.validator.un" +
"obtrusive.parse($(\"#editItemForm\"));\r\n            $(\'#editItemForm\')\r\n          " +
"      .on(\'click\',\'.btn-primary\',\r\n                function (e) {\r\n             " +
"       e.preventDefault();\r\n                    $(this).closest(\'form\').submit()" +
";\r\n                });\r\n            $(\'#listeditor\').modal(\'show\');\r\n        }\r\n" +
"    </script>\r\n");

            
            #line 185 "..\..\Views\Events\_Admin.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
