#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Events\AddEditEvent.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Events\AddEditEvent.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\Events\AddEditEvent.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Events\AddEditEvent.cshtml"
    using Snitz.Base;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Events\AddEditEvent.cshtml"
    using SnitzConfig;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Events\AddEditEvent.cshtml"
    using SnitzDataModel.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Events\AddEditEvent.cshtml"
    using SnitzEvents.Views.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Events/AddEditEvent.cshtml")]
    public partial class _Views_Events_AddEditEvent_cshtml : System.Web.Mvc.WebViewPage<SnitzEvents.ViewModels.ClubEventViewModel>
    {
        public _Views_Events_AddEditEvent_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Events\AddEditEvent.cshtml"
Write(Styles.Render("~/Content/jquery-ui.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Events\AddEditEvent.cshtml"
Write(Styles.Render("~/Content/jquery-ui-timepicker-addon.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Events\AddEditEvent.cshtml"
Write(Html.Raw(Config.ThemeCss("fullcalendar.min.css")));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n\r\n");

            
            #line 17 "..\..\Views\Events\AddEditEvent.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Events\AddEditEvent.cshtml"
     using (Html.BeginForm("AddEditEvent", "Events", FormMethod.Post, new { @class = "form form-horizontal" }))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblEventTitle", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\Events\AddEditEvent.cshtml"
           Write(Html.TextBoxFor(model => model.Title, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblStartDate", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Views\Events\AddEditEvent.cshtml"
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Events\AddEditEvent.cshtml"
                 if (Model.StartDate.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control club-dates\"");

WriteLiteral(" id=\"calendar-start-date\"");

WriteLiteral(" name=\"StartDate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1298), Tuple.Create("\"", 1352)
            
            #line 30 "..\..\Views\Events\AddEditEvent.cshtml"
                                        , Tuple.Create(Tuple.Create("", 1306), Tuple.Create<System.Object, System.Int32>(Model.StartDate.Value.ToString("dd MMM yyyy")
            
            #line default
            #line hidden
, 1306), false)
);

WriteLiteral(" />\r\n");

            
            #line 31 "..\..\Views\Events\AddEditEvent.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control club-dates\"");

WriteLiteral(" id=\"calendar-start-date\"");

WriteLiteral(" name=\"StartDate\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n");

            
            #line 35 "..\..\Views\Events\AddEditEvent.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblEndDate", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

            
            #line 42 "..\..\Views\Events\AddEditEvent.cshtml"
                
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Events\AddEditEvent.cshtml"
                 if (Model.EndDate.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control club-dates\"");

WriteLiteral(" id=\"calendar-end-date\"");

WriteLiteral(" name=\"EndDate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1972), Tuple.Create("\"", 2024)
            
            #line 44 "..\..\Views\Events\AddEditEvent.cshtml"
                                    , Tuple.Create(Tuple.Create("", 1980), Tuple.Create<System.Object, System.Int32>(Model.EndDate.Value.ToString("dd MMM yyyy")
            
            #line default
            #line hidden
, 1980), false)
);

WriteLiteral(" />\r\n");

            
            #line 45 "..\..\Views\Events\AddEditEvent.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control club-dates\"");

WriteLiteral(" id=\"calendar-end-date\"");

WriteLiteral(" name=\"EndDate\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n");

            
            #line 49 "..\..\Views\Events\AddEditEvent.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 54 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblEventCategory", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\Events\AddEditEvent.cshtml"
           Write(Html.RadioButtonForSelectList(model => model.CatId, new SelectList(Model.Categories, "Key", "Value"), Enumerators.Position.Horizontal));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");

WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblEventClub", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 63 "..\..\Views\Events\AddEditEvent.cshtml"
           Write(Html.DropDownListFor(model => model.ClubId, new SelectList(Model.Clubs, "Key", "Value"), new { @class = "form-control", @tabindex = 1 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblEventLocation", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 69 "..\..\Views\Events\AddEditEvent.cshtml"
           Write(Html.DropDownListFor(model => model.LocId, new SelectList(Model.Locations, "Key", "Value"), new { @class = "form-control", @tabindex = 1 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label col-xs-2\"");

WriteLiteral(">");

            
            #line 73 "..\..\Views\Events\AddEditEvent.cshtml"
                                             Write(ResourceManager.GetLocalisedString("lblEventDetails", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"col-xs-7\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"editorDiv\"");

WriteLiteral(">\r\n");

            
            #line 76 "..\..\Views\Events\AddEditEvent.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Events\AddEditEvent.cshtml"
                     if (ViewData["noToolbar"] == null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Events\AddEditEvent.cshtml"
                                          Write(Html.Partial("_EditorBar", Model, new ViewDataDictionary(this.ViewData) { { "buttons", new List<string>() } }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 79 "..\..\Views\Events\AddEditEvent.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"qr-editor-field col-xs-12\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" oninput=\"isTyping()\"");

WriteLiteral(" class=\"bbc-code-editor multi-line form-control\"");

WriteLiteral(" id=\"Message\"");

WriteLiteral(" data-val-required=\"Message is Required\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\Events\AddEditEvent.cshtml"
                                                                                                                                                                                          Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                        <div");

WriteLiteral(" id=\"popup-btns\"");

WriteLiteral(" class=\"btn-toolbar editor-buttons\"");

WriteLiteral(" role=\"toolbar\"");

WriteLiteral(" style=\"position: absolute;top:0;right:0;margin-right:15px;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"btn-group btn-group-sm\"");

WriteLiteral(">\r\n");

            
            #line 85 "..\..\Views\Events\AddEditEvent.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\Events\AddEditEvent.cshtml"
                                 if (ClassicConfig.GetValue("STRALLOWUPLOADS") == "1")
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4816), Tuple.Create("\"", 4856)
            
            #line 87 "..\..\Views\Events\AddEditEvent.cshtml"
, Tuple.Create(Tuple.Create("", 4823), Tuple.Create<System.Object, System.Int32>(Url.Action("FileUpload", "Home")
            
            #line default
            #line hidden
, 4823), false)
);

WriteLiteral(" class=\"btn btn-default modal-link\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4892), Tuple.Create("\"", 4959)
            
            #line 87 "..\..\Views\Events\AddEditEvent.cshtml"
                                          , Tuple.Create(Tuple.Create("", 4900), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("tipAttach", "Tooltip")
            
            #line default
            #line hidden
, 4900), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-paperclip\"");

WriteLiteral("></span></a>\r\n");

            
            #line 88 "..\..\Views\Events\AddEditEvent.cshtml"

                                    if (ClassicConfig.GetValue("STRPHOTOALBUM") == "1" || ClassicConfig.GetValue("INTCOMMONALBUM") == "1")
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5227), Tuple.Create("\"", 5291)
            
            #line 91 "..\..\Views\Events\AddEditEvent.cshtml"
, Tuple.Create(Tuple.Create("", 5234), Tuple.Create<System.Object, System.Int32>(Url.Action("UploadFile", "PhotoAlbum",new{fields=false})
            
            #line default
            #line hidden
, 5234), false)
);

WriteLiteral(" class=\"btn btn-default gallery-link\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5351), Tuple.Create("\"", 5421)
            
            #line 91 "..\..\Views\Events\AddEditEvent.cshtml"
                                                                                              , Tuple.Create(Tuple.Create("", 5359), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("tipUpload", "PhotoAlbum")
            
            #line default
            #line hidden
, 5359), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-file-image-o\"");

WriteLiteral("></span></a>\r\n");

            
            #line 92 "..\..\Views\Events\AddEditEvent.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n                        </div>\r\n             " +
"       </div>\r\n                    <div");

WriteLiteral(" class=\"hidden-xs col-sm-12\"");

WriteLiteral(">\r\n");

            
            #line 98 "..\..\Views\Events\AddEditEvent.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 98 "..\..\Views\Events\AddEditEvent.cshtml"
                         if (ClassicConfig.EmoticonTable)
                        {
                            
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Events\AddEditEvent.cshtml"
                       Write(Html.Partial("_emoticons", Emoticon.Emoticons()));

            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Events\AddEditEvent.cshtml"
                                                                             
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n            </div>\r\n\r\n\r\n " +
"       </div>\r\n");

            
            #line 110 "..\..\Views\Events\AddEditEvent.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 112 "..\..\Views\Events\AddEditEvent.cshtml"
       Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"col-xs-7\"");

WriteLiteral(">");

            
            #line 114 "..\..\Views\Events\AddEditEvent.cshtml"
                             Write(Html.ValidationSummary(false, "", new { @class = "list-group-item-info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group col-xs-9 padding-md pull-right\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6340), Tuple.Create("\"", 6406)
            
            #line 118 "..\..\Views\Events\AddEditEvent.cshtml"
, Tuple.Create(Tuple.Create("", 6348), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("btnCancel", "labels")
            
            #line default
            #line hidden
, 6348), false)
);

WriteLiteral(" class=\"btn btn-sm btn-warning cancel\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"reset\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6481), Tuple.Create("\"", 6546)
            
            #line 119 "..\..\Views\Events\AddEditEvent.cshtml"
, Tuple.Create(Tuple.Create("", 6489), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("btnReset", "labels")
            
            #line default
            #line hidden
, 6489), false)
);

WriteLiteral(" class=\"btn btn-sm btn-primary\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6615), Tuple.Create("\"", 6679)
            
            #line 120 "..\..\Views\Events\AddEditEvent.cshtml"
, Tuple.Create(Tuple.Create("", 6623), Tuple.Create<System.Object, System.Int32>(ResourceManager.GetLocalisedString("btnSave", "labels")
            
            #line default
            #line hidden
, 6623), false)
);

WriteLiteral(" class=\"btn btn-sm btn-success\"");

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 122 "..\..\Views\Events\AddEditEvent.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 128 "..\..\Views\Events\AddEditEvent.cshtml"
Write(Scripts.Render("~/Scripts/jquery-ui-timepicker-addon.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 129 "..\..\Views\Events\AddEditEvent.cshtml"
Write(Scripts.Render("~/Scripts/snitz.cal.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 130 "..\..\Views\Events\AddEditEvent.cshtml"
    
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Events\AddEditEvent.cshtml"
     if (Session["Culture"] != null && Session["Culture"].ToString() != "en")
    {
        
            
            #line default
            #line hidden
            
            #line 132 "..\..\Views\Events\AddEditEvent.cshtml"
   Write(Scripts.Render("~/Scripts/lang/" + Session["Culture"] + ".js"));

            
            #line default
            #line hidden
            
            #line 132 "..\..\Views\Events\AddEditEvent.cshtml"
                                                                       
    }

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var timer = null;
        function isTyping() {
            clearTimeout(timer);
            var value = $('#Message').val();
            if (value) {
                $(""#popup-btns"").hide();
                timer = setTimeout(notTyping, 2000);// that's 2 seconds of not typing
            }
            else {
                notTyping();
            }
        }

        function notTyping() {
            $(""#popup-btns"").show();
        }        
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
