#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Events\Index.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    #line 3 "..\..\Views\Events\Index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    
    #line 2 "..\..\Views\Events\Index.cshtml"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Events\Index.cshtml"
    using LangResources.Utility;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Events\Index.cshtml"
    using SnitzConfig;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Events\Index.cshtml"
    using SnitzCore.Utility;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Views\Events\Index.cshtml"
    using SnitzEvents.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Events\Index.cshtml"
    using SnitzMembership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Events/Index.cshtml")]
    public partial class _Views_Events_Index_cshtml : System.Web.Mvc.WebViewPage<SnitzEvents.ViewModels.AgendaViewModel>
    {
        public _Views_Events_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Events\Index.cshtml"
  
    CultureInfo ci = SessionData.Get<CultureInfo>("Culture");
    string clang = ci.TwoLetterISOLanguageName;
    ViewBag.Title = ClassicConfig.ForumTitle + " | " + ResourceManager.GetLocalisedString("PluginTitle", "Events");
    string[] rtlLangs = new string[] { "ar", "arc", "dv", "fa", "ha", "khw", "ks", "ku", "ps", "ur", "yi", "he" };
    string[] arabic = new string[] { "ar", "arc", "dv", "fa", "ha", "khw", "ks", "ku", "ps", "ur" }; //Cairo
    string[] aramaic = new string[] { "yi", "he" }; //Tinos

    bool isRighToLeft = (rtlLangs.Contains(clang));

    if (!SessionData.Contains("isRighToLeft") || isRighToLeft != SessionData.Get<bool>("isRighToLeft"))
    {
        SessionData.Set("isRighToLeft", isRighToLeft);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Events\Index.cshtml"
Write(Styles.Render("~/Content/jquery-ui-timepicker-addon.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Views\Events\Index.cshtml"
Write(Html.Raw(Config.ThemeCss("plugincss/fullcalendar.min.css")));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 30 "..\..\Views\Events\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Events\Index.cshtml"
     if (isRighToLeft)
    {
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Events\Index.cshtml"
   Write(Styles.Render("~/Content/plugincss/fullcalendar-rtl.css"));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Events\Index.cshtml"
                                                                  
    }

            
            #line default
            #line hidden
});

DefineSection("sidebox", () => {

WriteLiteral("\r\n    <p></p>\r\n    <div");

WriteLiteral(" class=\"panel-group\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"panel panel-primary side-box hidden-xs\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\Events\Index.cshtml"
                                  Write(ResourceManager.GetLocalisedString("EventCategories", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1585), Tuple.Create("\"", 1628)
            
            #line 42 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1592), Tuple.Create<System.Object, System.Int32>(Url.Action("Index",new{id=0,old=0})
            
            #line default
            #line hidden
, 1592), false)
);

WriteLiteral(">");

            
            #line 42 "..\..\Views\Events\Index.cshtml"
                                                          Write(ResourceManager.GetLocalisedString("UpcomingEvents", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</a><span");

WriteLiteral(" title=\"Number of events\"");

WriteLiteral("></span><br />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1761), Tuple.Create("\"", 1818)
            
            #line 43 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1768), Tuple.Create<System.Object, System.Int32>(Url.Action("Index",new{id=-1,old=ViewBag.OldNew})
            
            #line default
            #line hidden
, 1768), false)
);

WriteLiteral(">");

            
            #line 43 "..\..\Views\Events\Index.cshtml"
                                                                        Write(ResourceManager.GetLocalisedString("PastEvents", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</a><span");

WriteLiteral(" title=\"Number of events\"");

WriteLiteral("></span><br />\r\n                <hr");

WriteLiteral(" class=\"title\"");

WriteLiteral(" />\r\n");

            
            #line 45 "..\..\Views\Events\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Events\Index.cshtml"
                 foreach (var cat in ViewBag.CatSummary)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2066), Tuple.Create("\"", 2130)
            
            #line 47 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2073), Tuple.Create<System.Object, System.Int32>(Url.Action("Index",new{id=cat.CatId,old=ViewBag.OldNew})
            
            #line default
            #line hidden
, 2073), false)
);

WriteLiteral(" class=\"catFilter\"");

WriteLiteral(" data-id=\"");

            
            #line 47 "..\..\Views\Events\Index.cshtml"
                                                                                                              Write(cat.CatId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\Events\Index.cshtml"
                                                                                                                          Write(cat.Name);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 47 "..\..\Views\Events\Index.cshtml"
                                                                                                                                     Write(cat.EventCount);

            
            #line default
            #line hidden
WriteLiteral(")</a>");

WriteLiteral("<br />\r\n");

            
            #line 48 "..\..\Views\Events\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel panel-primary side-box hidden-xs\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">");

            
            #line 52 "..\..\Views\Events\Index.cshtml"
                                  Write(ResourceManager.GetLocalisedString("EventFilter", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 58 "..\..\Views\Events\Index.cshtml"
               Write(Html.DropDownListFor(model => model.ClubId, new SelectList(Model.Clubs, "Key", "Value"), @ResourceManager.GetLocalisedString("AllClubs", "Events"), new { @class = "form-control", tabindex = 1, id = "club-filter", onchange = "filterClub();" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Views\Events\Index.cshtml"
               Write(Html.DropDownListFor(model => model.LocId, new SelectList(Model.Locations, "Key", "Value"), @ResourceManager.GetLocalisedString("AllLocations", "Events"), new { @class = "form-control", tabindex = 1, id = "loc-filter", onchange = "filterLocation();" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3528), Tuple.Create("\"", 3551)
            
            #line 63 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3536), Tuple.Create<System.Object, System.Int32>(ViewBag.OldNew
            
            #line default
            #line hidden
, 3536), false)
);

WriteLiteral(" id=\"old-new\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n");

            
            #line 66 "..\..\Views\Events\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Events\Index.cshtml"
         if (WebSecurity.IsAuthenticated)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-primary side-box hidden-xs\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">");

            
            #line 69 "..\..\Views\Events\Index.cshtml"
                                      Write(ResourceManager.GetLocalisedString("Other", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 71 "..\..\Views\Events\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Events\Index.cshtml"
                     if (String.IsNullOrWhiteSpace(ClassicConfig.GetValue("STRRESTRICTROLES")))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4019), Tuple.Create("\"", 4067)
            
            #line 73 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4026), Tuple.Create<System.Object, System.Int32>(Url.Action("AddEditEvent", new {id = 0})
            
            #line default
            #line hidden
, 4026), false)
);

WriteLiteral(">");

            
            #line 73 "..\..\Views\Events\Index.cshtml"
                                                                       Write(ResourceManager.GetLocalisedString("AddEvent", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("                        <br />\r\n");

            
            #line 75 "..\..\Views\Events\Index.cshtml"
                    }
                    else if (SnitzMembership.WebSecurity.IsUserInRole(WebSecurity.CurrentUserName, Model.AllowedRoles))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4357), Tuple.Create("\"", 4405)
            
            #line 78 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4364), Tuple.Create<System.Object, System.Int32>(Url.Action("AddEditEvent", new {id = 0})
            
            #line default
            #line hidden
, 4364), false)
);

WriteLiteral(">");

            
            #line 78 "..\..\Views\Events\Index.cshtml"
                                                                       Write(ResourceManager.GetLocalisedString("AddEvent", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("                        <br />\r\n");

            
            #line 80 "..\..\Views\Events\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4547), Tuple.Create("\"", 4578)
            
            #line 81 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4554), Tuple.Create<System.Object, System.Int32>(Url.Action("EventSubs")
            
            #line default
            #line hidden
, 4554), false)
);

WriteLiteral(">");

            
            #line 81 "..\..\Views\Events\Index.cshtml"
                                                  Write(ResourceManager.GetLocalisedString("MySubs", "Events"));

            
            #line default
            #line hidden
WriteLiteral("</a><br />\r\n                </div>\r\n            </div>\r\n");

            
            #line 84 "..\..\Views\Events\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4768), Tuple.Create("\"", 4794)
            
            #line 89 "..\..\Views\Events\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4776), Tuple.Create<System.Object, System.Int32>(ViewBag.CatFilter
            
            #line default
            #line hidden
, 4776), false)
);

WriteLiteral(" id=\"cat_filter\"");

WriteLiteral(" />\r\n    <div");

WriteLiteral(" id=\"calendar\"");

WriteLiteral("></div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var upComingEventsTitle = \'[");

            
            #line 94 "..\..\Views\Events\Index.cshtml"
                               Write(ResourceManager.GetLocalisedString("upComingEventTitle", "Events"));

            
            #line default
            #line hidden
WriteLiteral("]\';\r\n        var pastEventsTitle = \'[");

            
            #line 95 "..\..\Views\Events\Index.cshtml"
                           Write(ResourceManager.GetLocalisedString("upPastEventsTitle", "Events"));

            
            #line default
            #line hidden
WriteLiteral("]\';\r\n\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 98 "..\..\Views\Events\Index.cshtml"
Write(Scripts.Render("~/Scripts/moment.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 99 "..\..\Views\Events\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 99 "..\..\Views\Events\Index.cshtml"
     if (clang == "fa")
    {
        
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Events\Index.cshtml"
   Write(Scripts.Render("~/Scripts/moment-jalaali.min.js"));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Events\Index.cshtml"
                                                          
    }
    
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Events\Index.cshtml"
                                                                  

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 104 "..\..\Views\Events\Index.cshtml"
Write(Scripts.Render("~/Scripts/pluginjs/fullcalendar-year.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 105 "..\..\Views\Events\Index.cshtml"
Write(Scripts.Render("~/Scripts/lang/" + clang + ".js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 106 "..\..\Views\Events\Index.cshtml"
Write(Scripts.Render("~/Scripts/pluginjs/snitz.cal.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document)\r\n            .ready(function () {\r\n                var fil" +
"ter = $(\'#cat_filter\').val();\r\n                if (filter === \'-1\') {\r\n         " +
"           ClubCalendar(\"");

            
            #line 113 "..\..\Views\Events\Index.cshtml"
                             Write(Url.Action("GetClubCalendarEvents",new{id=-1,old=-1 }));

            
            #line default
            #line hidden
WriteLiteral("\", \'calendar\',\'");

            
            #line 113 "..\..\Views\Events\Index.cshtml"
                                                                                                   Write(ViewBag.StartDate);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                } else {\r\n                    if ($(\'#old-new\').val() === \'-" +
"1\') {\r\n                        ClubCalendar(\"");

            
            #line 116 "..\..\Views\Events\Index.cshtml"
                                 Write(Url.Action("GetClubCalendarEvents",new{id=ViewBag.CatFilter,old=-1}));

            
            #line default
            #line hidden
WriteLiteral("\", \'calendar\', \'");

            
            #line 116 "..\..\Views\Events\Index.cshtml"
                                                                                                                      Write(ViewBag.StartDate);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                    } else {\r\n                        ClubCalendar(\"");

            
            #line 118 "..\..\Views\Events\Index.cshtml"
                                 Write(Url.Action("GetClubCalendarEvents",new{id=ViewBag.CatFilter,old=0}));

            
            #line default
            #line hidden
WriteLiteral(@""", 'calendar','');
                    }

                }
                $('.del-event')
                    .on('click',
                        function (e) {
                            e.preventDefault();
                            var data = {};
                            data.id = $(this).data(""id"");

                            BootstrapDialog.confirm({
                                title: '");

            
            #line 130 "..\..\Views\Events\Index.cshtml"
                                   Write(ResourceManager.GetLocalisedString("lblDeleteEvent", "Events"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                message: \'");

            
            #line 131 "..\..\Views\Events\Index.cshtml"
                                     Write(ResourceManager.GetLocalisedString("msgDeleteEvent", "Events"));

            
            #line default
            #line hidden
WriteLiteral(@"<br/>', callback: function (ok) {
                                    if (ok) {
                                        $.ajax({
                                            url: window.SnitzVars.baseUrl + 'Events/RemoveEvent',
                                            data: data,
                                            type: ""POST"",
                                            cache: false,
                                            success: function (response) {

                                                window.location.reload();
                                            },
                                            error: function (jqXHR, textStatus, errorThrown) {
                                                BootstrapDialog.show({
                                                    type: BootstrapDialog.TYPE_WARNING,
                                                    title: textStatus,
                                                    message: jqXHR.responseText
                                                });

                                            }
                                        });
                                    }
                                }
                            });
                    });

                ");

WriteLiteral(@"
            });
        function filterClub() {
            alert($('#club-filter option:selected').text());
            $(""li[data-club!='"" + $('#club-filter option:selected').text() + ""']"").hide();
            $(""li[data-club='"" + $('#club-filter option:selected').text() + ""']"").show();
            $("".dropdown"").show();
        }
        function filterLocation() {
            alert($('#loc-filter option:selected').val());
            $(""li[data-loc!='"" + $('#loc-filter option:selected').text() + ""']"").hide();
            $(""li[data-loc='"" + $('#loc-filter option:selected').text() + ""']"").show();
            $("".dropdown"").show();
        }

    </script>
");

});

        }
    }
}
#pragma warning restore 1591
